"""Single parameter authority for Orbit Gobbler geometry."""

import math
import cadfits

# Manufacturing [sealed/derived]
NOZZLE = 0.4
MIN_WALL = 2.0 * NOZZLE
WALL = 4.0
RUN_CLEAR = 0.20
FREE_CLEAR = 0.40
FUSE_OVERLAP = 0.20

# Envelope [sealed]
BASE_W = 190.0
BASE_D = 70.0
BASE_H = 10.0
ASSEMBLED_H = 200.0
ORBIT_Z = 106.0
FRAME_R = 94.0
FRAME_T = 4.0
FRAME_REAR_Y = 29.9
FRAME_RING_W = 8.0
FRAME_FOOT_W = 22.0
FRAME_FOOT_H = 21.0
FRAME_FOOT_Y0 = -96.0
BEZEL_POST_D = 5.6
FRAME_PILOT_D = cadfits.slot_for(BEZEL_POST_D, RUN_CLEAR)
FRAME_HUB_R = 10.0
FRAME_STRUT_W = 5.0
FRAME_STRUT_ANGLES = (0.0, 90.0, 180.0, 270.0)

# Frame/base derived mates
FRAME_TENON_W = 18.0
FRAME_TENON_T = 4.0
FRAME_TENON_H = 6.5
FRAME_TENON_Y0 = -100.0
FRAME_TENON_X = 50.0
FRAME_MORTISE_T = cadfits.slot_for(FRAME_TENON_T, RUN_CLEAR)
FRAME_MORTISE_W = cadfits.slot_for(FRAME_TENON_W, RUN_CLEAR)
KEY_T = 3.8
KEY_W = 7.0
FRAME_KEY_L = 14.0
FRAME_KEY_SLOT_T = cadfits.slot_for(KEY_T, RUN_CLEAR)
FRAME_KEY_SLOT_L = cadfits.slot_for(FRAME_KEY_L, RUN_CLEAR)
FRAME_KEY_LOCAL_Y = -98.0
FRAME_MORTISE_DEPTH = 6.0
WASHER_OD = 16.0
WASHER_T = 2.0
EYE_FRONT_Y = 2.6
CARRIER_WASHER_REAR_Y = 7.8
CARRIER_KEY_REAR_Y = 2.4
PINION_KEY_REAR_Y = -2.3
GRIP_KEY_GAP = 0.20
KEY_L = 14.0
KEY_D = 3.2
KEY_SLOT_D = cadfits.slot_for(KEY_D, RUN_CLEAR)
KEY_SLOT_L = cadfits.slot_for(KEY_L, RUN_CLEAR)
KEY_SLOT_W = cadfits.slot_for(KEY_W, RUN_CLEAR)
KEY_SLOT_T = cadfits.slot_for(KEY_T, RUN_CLEAR)

# Cam [sealed]
INNER_ORBIT_R = 58.0
OUTER_MOUTH_R = 70.0
MOON_R = 12.0
CAM_GROOVE_W = 9.0
CAM_WALL = 2.4
CAM_HEIGHT = 6.5
CAM_SAMPLES = 180

# Gears [sealed]
GEAR_MODULE = 1.25
PRESSURE_ANGLE_DEG = 20.0
CARRIER_TEETH = 40
PINION_TEETH = 20
GEAR_FACE = 5.0
GEAR_BACKLASH = 0.22
CARRIER_PITCH_R = GEAR_MODULE * CARRIER_TEETH / 2.0
PINION_PITCH_R = GEAR_MODULE * PINION_TEETH / 2.0
GEAR_CENTER_DISTANCE = CARRIER_PITCH_R + PINION_PITCH_R
PINION_X = -GEAR_CENTER_DISTANCE
GEAR_TIP_ALLOWANCE = 0.90
GEAR_ROOT_ALLOWANCE = 1.10
GEAR_FLANK_SAMPLES = 7
GEAR_TIP_SAMPLES = 5

# Carrier and slider [sealed/derived]
CARRIER_FRONT_Y = 8.0
SPOKE_DECK_T = 4.4
DECK_GAP = 2.0
GEAR_DECK_Z0 = SPOKE_DECK_T + DECK_GAP
CARRIER_T = GEAR_DECK_Z0 + GEAR_FACE
CARRIER_ENDPLAY = 0.45
CARRIER_BORE = cadfits.slot_for(8.0, 0.175)
CARRIER_ACTIVE_R0 = 30.0
CARRIER_ACTIVE_R1 = 88.0
CARRIER_HUB_R = 15.0
CARRIER_ROOT_COLLAR_R = 24.0
CARRIER_SPOKE_W = 20.0
CARRIER_BALANCE_W = 12.0
CARRIER_BALANCE_R1 = 60.0
CARRIER_BALANCE_ANGLES = (120.0, 240.0)
CHANNEL_FLOOR_T = 1.2
CHANNEL_THROAT_Z0 = 2.4
SLIDER_LENGTH = 34.0
SLIDER_BASE_W = 12.0
SLIDER_THROAT_W = 9.8
SLIDER_T = 3.2
SLIDER_BASE_T = 1.1
CHANNEL_BASE_W = cadfits.slot_for(SLIDER_BASE_W, 0.30)
CHANNEL_THROAT_W = cadfits.slot_for(SLIDER_THROAT_W, 0.30)
CHANNEL_R1 = 83.0
CHANNEL_END_MATERIAL = CARRIER_ACTIVE_R1 - CHANNEL_R1
FOLLOWER_SLOT_W = cadfits.slot_for(6.0, 0.30)
FOLLOWER_PATH_R0 = 57.0
FOLLOWER_PATH_R1 = 71.0
SLIDER_CENTER_R = (FOLLOWER_PATH_R0 + FOLLOWER_PATH_R1) / 2.0
FOLLOWER_LOCAL_X = OUTER_MOUTH_R - SLIDER_CENTER_R
FOLLOWER_OVERTRAVEL = 1.0
FOLLOWER_END_MATERIAL = 3.6
FOLLOWER_D = 8.0
FOLLOWER_BORE = cadfits.slot_for(5.0, 0.15)
FOLLOWER_AXLE_D = 5.0
FOLLOWER_AXLE_L = 18.5
FOLLOWER_ROLLER_T = 4.0
FOLLOWER_FRONT_Y = 4.3
FOLLOWER_ROLLER_Y = 19.6
FOLLOWER_SHAFT_FLAT = 1.6
MOON_T = 5.0
MOON_FRONT_Y = 2.5
MOON_PILOT_D = 8.0
MOON_PILOT_CLEAR_D = cadfits.slot_for(MOON_PILOT_D, 0.20)
MOON_PILOT_DEPTH = 3.2
MOON_LUG_W = 2.4
MOON_LUG_L_SHORT = 2.6
MOON_LUG_L_LONG = 4.0
REST_ANGLE_DEG = 43.0

# Axles, guards, crank [sealed/derived]
CENTRAL_AXLE_D = 8.0
CENTRAL_AXLE_L = 36.6
CENTRAL_FLANGE_D = 18.0
CENTRAL_FLANGE_T = 3.0
CENTRAL_AXLE_REAR_Y = 33.1
EYE_D = 56.0
EYE_T = 3.0
PINION_POST_D = 8.0
PINION_BORE = cadfits.slot_for(PINION_POST_D, 0.175)
PINION_SLEEVE_D = 10.0
PINION_FRAME_BORE = cadfits.slot_for(PINION_SLEEVE_D, RUN_CLEAR)
PINION_WASHER_BORE = cadfits.slot_for(PINION_SLEEVE_D, RUN_CLEAR)
PINION_FRONT_Y = 14.4
PINION_SLEEVE_L = 31.3
PINION_PHASE_DEG = 12.0
D_FLAT_X = 3.2
CRANK_D_BORE = cadfits.slot_for(PINION_SLEEVE_D, 0.15)
CRANK_ARM_L = 38.0
CRANK_ARM_W = 10.0
CRANK_ARM_T = 4.0
CRANK_HUB_D = 32.0
CRANK_ARM_OFFSET_DEG = 72.0
CRANK_ASSEMBLY_ANGLE_DEG = -PINION_PHASE_DEG + CRANK_ARM_OFFSET_DEG
CRANK_HUB_BORE_D = cadfits.slot_for(PINION_SLEEVE_D, 0.15)
CRANK_REAR_Y = 34.3
CRANK_GRIP_X = CRANK_ARM_L
CRANK_GRIP_WORLD_X = PINION_X + CRANK_ARM_L * math.cos(math.radians(CRANK_ASSEMBLY_ANGLE_DEG))
CRANK_GRIP_WORLD_Z = ORBIT_Z + CRANK_ARM_L * math.sin(math.radians(CRANK_ASSEMBLY_ANGLE_DEG))
GRIP_POST_D = 8.0
GRIP_BORE = cadfits.slot_for(GRIP_POST_D, RUN_CLEAR)
SMALL_WASHER_BORE = cadfits.slot_for(max(CENTRAL_AXLE_D, GRIP_POST_D), RUN_CLEAR)
GRIP_D = 14.0
GRIP_L = 22.0
GRIP_POST_L = 33.2
RETAINER_SOLID = 1.5
RETAINER_LIGAMENT = 1.8
CLIP_T = 2.0
CLIP_GROOVE_W = cadfits.slot_for(CLIP_T, RUN_CLEAR)
CLIP_GROOVE_DEPTH = 0.8
CENTRAL_GROOVE_CORE_D = CENTRAL_AXLE_D - 2.0 * CLIP_GROOVE_DEPTH
PINION_GROOVE_CORE_D = PINION_SLEEVE_D - 2.0 * CLIP_GROOVE_DEPTH
GRIP_GROOVE_CORE_D = GRIP_POST_D - 2.0 * CLIP_GROOVE_DEPTH
CENTRAL_CLIP_Z0 = CENTRAL_FLANGE_T + CENTRAL_AXLE_L - RETAINER_SOLID - CLIP_GROOVE_W
PINION_CLIP_Z0 = PINION_SLEEVE_L - RETAINER_SOLID - CLIP_GROOVE_W
GRIP_CLIP_Z0 = CRANK_ARM_T + GRIP_POST_L - RETAINER_SOLID - CLIP_GROOVE_W
SMALL_CLIP_ID = cadfits.slot_for(max(CENTRAL_GROOVE_CORE_D, GRIP_GROOVE_CORE_D), RUN_CLEAR)
PINION_CLIP_ID = PINION_GROOVE_CORE_D + 0.4
SMALL_CLIP_OD = 14.0
PINION_CLIP_OD = 16.0
SMALL_CLIP_OPENING = 6.2
PINION_CLIP_OPENING = 8.2

# Mouth [sealed]
LIP_R_IN = 62.0
LIP_R_OUT = 86.4
LIP_T = 3.0
LIP_STANDOFF_R = 90.0
LIP_STANDOFF_RADIAL = 4.0
LIP_STANDOFF_TANGENTIAL = 8.0
LIP_STANDOFF_L = 24.9
UPPER_LIP_A0 = 4.0
UPPER_LIP_A1 = 42.0
LOWER_LIP_A0 = 46.0
LOWER_LIP_A1 = 88.0
BEZEL_JOIN_R0 = 86.0
BEZEL_JOIN_R1 = 94.0
LIP_FRONT_Y = -2.0
BEZEL_PILOT_ANGLES = (10.0, 34.0, 58.0, 82.0)

# Bracing [derived]
BRACE_X = 72.0
BRACE_T = 4.0
BRACE_RUN = 34.0
BRACE_RISE = 58.0
BRACE_FOOT_W = BRACE_RUN
BRACE_SLOT_W = cadfits.slot_for(BRACE_T, RUN_CLEAR)
BRACE_SLOT_L = cadfits.slot_for(BRACE_FOOT_W, RUN_CLEAR)
BRACE_BASE_Y = -18.0
BRACE_BASE_Z = BASE_H

# Presentation colours (sRGB hex converted by cadgen.srgb)
COLOR_BASE = "#253047"
COLOR_BODY = "#465A73"
COLOR_CAM = "#7587A0"
COLOR_DRIVE = "#D78A2E"
COLOR_MOON = "#D9D4B8"
COLOR_EYE = "#81D4C5"
COLOR_MOUTH = "#B65D6A"


def cam_radius(angle_deg: float) -> float:
    """Sealed 360-degree cosine cam centreline."""
    a = angle_deg % 360.0
    if 3.0 <= a < 39.0:
        u = (a - 3.0) / 36.0
        return INNER_ORBIT_R + (OUTER_MOUTH_R - INNER_ORBIT_R) * (1.0 - math.cos(math.pi * u)) / 2.0
    if 39.0 <= a < 47.0:
        return OUTER_MOUTH_R
    if 47.0 <= a < 83.0:
        u = (a - 47.0) / 36.0
        return OUTER_MOUTH_R - (OUTER_MOUTH_R - INNER_ORBIT_R) * (1.0 - math.cos(math.pi * u)) / 2.0
    return INNER_ORBIT_R


def polar_xy(radius: float, angle_deg: float) -> tuple[float, float]:
    """Clockwise degrees from 12 o'clock into local XY."""
    a = math.radians(angle_deg)
    return radius * math.sin(a), radius * math.cos(a)
