#!/usr/bin/env python3
"""Exercise the installed native Workshop CLI outside its source tree."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import zipfile


SCHEMA_OWNERS = {
    "artifact-manifest.schema.json": "artifacts",
    "inventor.schema.json": "contributors",
    "cad-project.schema.json": "make",
    "validator-policy.schema.json": "make",
    "verification-receipt.schema.json": "make",
    "receipt.schema.json": "runtime",
}
SKILLS = ("cad", "product-to-cad", "step-parts")
INVENTORS = ("alice", "bob", "eve", "ivy", "leo")


def _run(command, *, cwd: Path, environment=None) -> subprocess.CompletedProcess:
    completed = subprocess.run(
        [str(part) for part in command],
        cwd=str(cwd),
        env=environment,
        capture_output=True,
        text=True,
        timeout=180,
        check=False,
    )
    if completed.returncode != 0:
        raise AssertionError(
            "command failed (%d): %s\nstdout:\n%s\nstderr:\n%s"
            % (
                completed.returncode,
                " ".join(str(part) for part in command),
                completed.stdout,
                completed.stderr,
            )
        )
    return completed


def _python_path(venv: Path) -> Path:
    return venv / ("Scripts/python.exe" if os.name == "nt" else "bin/python")


def _workshop_path(venv: Path) -> Path:
    return venv / ("Scripts/workshop.exe" if os.name == "nt" else "bin/workshop")


def _build_wheel(repository: Path, root: Path) -> Path:
    wheelhouse = root / "wheelhouse"
    wheelhouse.mkdir()
    _run(
        (
            sys.executable,
            "-m",
            "pip",
            "wheel",
            "--no-build-isolation",
            "--no-deps",
            "--wheel-dir",
            wheelhouse,
            repository,
        ),
        cwd=repository,
    )
    wheels = tuple(wheelhouse.glob("autonomous_workshop-*.whl"))
    if len(wheels) != 1:
        raise AssertionError("expected exactly one Workshop wheel")
    return wheels[0]


def _audit_wheel(wheel: Path, repository: Path) -> None:
    with zipfile.ZipFile(wheel) as archive:
        infos = {item.filename: item for item in archive.infolist()}
        members = set(infos)
        if any(
            "/__pycache__/" in name or name.endswith((".pyc", ".pyo"))
            for name in members
        ):
            raise AssertionError("wheel contains generated bytecode")
        code_roots = {
            name.split("/", 1)[0]
            for name in members
            if name.endswith(".py") and ".dist-info/" not in name
        }
        if code_roots != {"cli", "workshop"}:
            raise AssertionError("unexpected Python packages: %r" % sorted(code_roots))
        for forbidden in (
            "autonomous_workshop/",
            "inventor_core/",
            "inventor_foundation/",
            "inventor_workshop/",
            "workshop_cli/",
            "tests/",
        ):
            if any(name.startswith(forbidden) for name in members):
                raise AssertionError("wheel contains removed tree %s" % forbidden)
        for required in (
            "cli/main.py",
            "workshop/runtime/_agent_assets/.agents/product-run/AGENTS.md",
            "workshop/runtime/_agent_assets/.agents/skills/autonomous-workshop/SKILL.md",
        ):
            if required not in members:
                raise AssertionError("wheel is missing %s" % required)

        skills = repository / "src" / "workshop" / "make" / "skills"
        for source in skills.rglob("*"):
            if not source.is_file() or "__pycache__" in source.parts:
                continue
            member = "workshop/make/skills/%s" % source.relative_to(skills).as_posix()
            if member not in infos or archive.read(member) != source.read_bytes():
                raise AssertionError("wheel skill differs: %s" % member)

        inventor_sources = repository / "inventors"
        expected_inventor_members = set()
        for inventor_id in INVENTORS:
            source_root = inventor_sources / inventor_id
            for source in source_root.rglob("*"):
                if not source.is_file() or source.is_symlink():
                    continue
                member = (
                    "workshop/contributors/_catalog/inventors/%s/%s"
                    % (inventor_id, source.relative_to(source_root).as_posix())
                )
                expected_inventor_members.add(member)
                if member not in infos or archive.read(member) != source.read_bytes():
                    raise AssertionError("wheel Inventor asset differs: %s" % member)
                source_executable = bool(source.stat().st_mode & 0o111)
                wheel_executable = bool((infos[member].external_attr >> 16) & 0o111)
                if source_executable != wheel_executable:
                    raise AssertionError(
                        "wheel Inventor executable mode differs: %s" % member
                    )
        observed_inventor_members = {
            name
            for name, info in infos.items()
            if name.startswith("workshop/contributors/_catalog/inventors/")
            and not info.is_dir()
        }
        if observed_inventor_members != expected_inventor_members:
            raise AssertionError("wheel Inventor catalog inventory differs")

        expected_schemas = {
            "workshop/%s/schemas/%s" % (owner, name)
            for name, owner in SCHEMA_OWNERS.items()
        }
        observed_schemas = {
            name
            for name in members
            if "/schemas/" in name and name.endswith(".schema.json")
        }
        if observed_schemas != expected_schemas:
            raise AssertionError("wheel schema inventory differs")


def _install_wheel(wheel: Path, root: Path) -> tuple[Path, Path]:
    venv = root / "venv"
    _run((sys.executable, "-m", "venv", venv), cwd=root)
    python = _python_path(venv)
    _run((python, "-m", "pip", "install", "--no-deps", wheel), cwd=root)
    return python, _workshop_path(venv)


def _json(command, *, cwd: Path, environment) -> object:
    return json.loads(_run(command, cwd=cwd, environment=environment).stdout)


def acceptance(wheel: Path, repository: Path) -> None:
    _audit_wheel(wheel, repository)
    with tempfile.TemporaryDirectory(prefix="workshop-installed-wheel-") as temporary:
        root = Path(temporary)
        away = root / "outside-checkout"
        away.mkdir()
        python, workshop = _install_wheel(wheel, root)
        environment = {
            name: os.environ[name]
            for name in (
                "HOME",
                "LANG",
                "LC_ALL",
                "LC_CTYPE",
                "PATH",
                "SYSTEMROOT",
                "TMPDIR",
            )
            if os.environ.get(name)
        }
        environment["WORKSHOP_HOME"] = str(root / "workshop-home")

        _run(
            (
                python,
                "-c",
                "import importlib.metadata as m; import workshop, cli.main; "
                "assert m.version('autonomous-workshop') == workshop.__version__",
            ),
            cwd=away,
            environment=environment,
        )
        skills = _json(
            (workshop, "skills", "list", "--json"),
            cwd=away,
            environment=environment,
        )
        if tuple(item["name"] for item in skills) != SKILLS:
            raise AssertionError("installed skill inventory is incomplete")
        schemas = set(
            _run(
                (workshop, "schemas", "list"), cwd=away, environment=environment
            ).stdout.splitlines()
        )
        if schemas != set(SCHEMA_OWNERS):
            raise AssertionError("installed schema inventory is incomplete")
        inventors = _json(
            (workshop, "inventors", "--json"), cwd=away, environment=environment
        )
        if tuple(item["id"] for item in inventors) != INVENTORS:
            raise AssertionError("installed inventor catalog is incomplete")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wheel", type=Path)
    args = parser.parse_args(argv)
    repository = Path(__file__).resolve().parents[2]
    if args.wheel is not None:
        acceptance(args.wheel.resolve(strict=True), repository)
    else:
        with tempfile.TemporaryDirectory(prefix="workshop-wheel-build-") as temporary:
            acceptance(_build_wheel(repository, Path(temporary)), repository)
    print("installed-wheel-cli: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
