#!/usr/bin/env python3
"""Exercise the installed native Workshop CLI outside its source tree."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import subprocess
import sys
import tempfile
import tomllib
import zipfile


SCHEMA_OWNERS = {
    "artifact-manifest.schema.json": "artifacts",
    "inventor.schema.json": "contributors",
    "cad-project.schema.json": "make",
    "validator-policy.schema.json": "make",
    "verification-receipt.schema.json": "make",
    "receipt.schema.json": "runtime",
}
SKILL_PATHS = {
    "cad": "make/skills/cad",
    "design-reference": "make/skills/design-reference",
    "design-vault": "invent/skills/design-vault",
    "electromechanical-integration": "make/skills/electromechanical-integration",
    "image-to-cad": "make/skills/image-to-cad",
    "manual-design": "release/skills/manual-design",
    "step-parts": "make/skills/step-parts",
}
SKILLS = tuple(SKILL_PATHS)
LISTED_MAKE_SKILLS = tuple(
    name for name, relative in SKILL_PATHS.items() if relative.startswith("make/")
)
INVENTORS = (
    "abo",
    "alice",
    "bob",
    "eve",
    "ivy",
    "kestrel-knot",
    "leo",
    "luma-vale",
    "mira-fold",
    "orin-shadow",
    "pico-press",
    "sonora-reed",
    "tess-loop",
    "vela-bloom",
)
CODEX_THREAD_ID = "12345678-1234-5678-9234-567812345678"


def _run(command, *, cwd: Path, environment=None) -> subprocess.CompletedProcess:
    completed = subprocess.run(
        [str(part) for part in command],
        cwd=str(cwd),
        env=environment,
        capture_output=True,
        text=True,
        timeout=180,
        check=False,
    )
    if completed.returncode != 0:
        raise AssertionError(
            "command failed (%d): %s\nstdout:\n%s\nstderr:\n%s"
            % (
                completed.returncode,
                " ".join(str(part) for part in command),
                completed.stdout,
                completed.stderr,
            )
        )
    return completed


def _python_path(venv: Path) -> Path:
    return venv / ("Scripts/python.exe" if os.name == "nt" else "bin/python")


def _workshop_path(venv: Path) -> Path:
    return venv / ("Scripts/workshop.exe" if os.name == "nt" else "bin/workshop")


def _source_files(root: Path) -> dict[str, Path]:
    files = {}
    for source in root.rglob("*"):
        if source.is_symlink():
            raise AssertionError("source asset is a symlink: %s" % source)
        relative = source.relative_to(root)
        if (
            "__pycache__" in relative.parts
            or ".git" in relative.parts
            or source.name == ".DS_Store"
            or source.name.endswith((".pyc", ".pyo"))
        ):
            continue
        if source.is_dir():
            continue
        if not source.is_file():
            raise AssertionError("source asset is not a regular file: %s" % source)
        files[relative.as_posix()] = source
    return files


def _zip_executable(info: zipfile.ZipInfo) -> bool:
    return bool((info.external_attr >> 16) & 0o111)


def _audit_zip_tree(
    archive: zipfile.ZipFile,
    infos: dict[str, zipfile.ZipInfo],
    *,
    source_root: Path,
    member_root: str,
) -> None:
    source_files = _source_files(source_root)
    expected = {member_root + "/" + relative for relative in source_files}
    observed = {
        name
        for name, info in infos.items()
        if name.startswith(member_root + "/") and not info.is_dir()
    }
    if observed != expected:
        raise AssertionError("wheel asset inventory differs: %s" % member_root)
    for relative, source in source_files.items():
        member = member_root + "/" + relative
        if archive.read(member) != source.read_bytes():
            raise AssertionError("wheel asset bytes differ: %s" % member)
        if _zip_executable(infos[member]) != bool(source.stat().st_mode & 0o111):
            raise AssertionError("wheel asset executable mode differs: %s" % member)


def _build_wheel(repository: Path, root: Path) -> Path:
    wheelhouse = root / "wheelhouse"
    wheelhouse.mkdir()
    _run(
        (
            sys.executable,
            "-m",
            "pip",
            "wheel",
            "--no-deps",
            "--wheel-dir",
            wheelhouse,
            repository,
        ),
        cwd=repository,
    )
    wheels = tuple(wheelhouse.glob("autonomous_workshop-*.whl"))
    if len(wheels) != 1:
        raise AssertionError("expected exactly one Workshop wheel")
    return wheels[0]


def _audit_wheel(wheel: Path, repository: Path) -> None:
    with zipfile.ZipFile(wheel) as archive:
        infos = {item.filename: item for item in archive.infolist()}
        members = set(infos)
        if any(
            "/__pycache__/" in name or name.endswith((".pyc", ".pyo"))
            for name in members
        ):
            raise AssertionError("wheel contains generated bytecode")
        code_roots = {
            name.split("/", 1)[0]
            for name in members
            if name.endswith(".py") and ".dist-info/" not in name
        }
        if code_roots != {"cli", "workshop"}:
            raise AssertionError("unexpected Python packages: %r" % sorted(code_roots))
        for forbidden in (
            "autonomous_workshop/",
            "inventor_core/",
            "inventor_foundation/",
            "inventor_workshop/",
            "workshop_cli/",
            "tests/",
        ):
            if any(name.startswith(forbidden) for name in members):
                raise AssertionError("wheel contains removed tree %s" % forbidden)
        for forbidden in (
            "workshop/removed_packaging_sentinel.py",
            "cli/removed_packaging_sentinel.py",
        ):
            if forbidden in members:
                raise AssertionError("wheel contains stale build output %s" % forbidden)
        for required in (
            "cli/main.py",
            "workshop/runtime/_agent_assets/.agents/product-run/AGENTS.md",
            (
                "workshop/runtime/_agent_assets/.agents/product-run/.agents/skills/"
                "autonomous-workshop/SKILL.md"
            ),
        ):
            if required not in members:
                raise AssertionError("wheel is missing %s" % required)

        _audit_zip_tree(
            archive,
            infos,
            source_root=repository / "src" / "workshop" / "make" / "skills",
            member_root="workshop/make/skills",
        )
        _audit_zip_tree(
            archive,
            infos,
            source_root=repository / "src" / "workshop" / "release" / "skills",
            member_root="workshop/release/skills",
        )
        _audit_zip_tree(
            archive,
            infos,
            source_root=repository / ".agents" / "product-run",
            member_root="workshop/runtime/_agent_assets/.agents/product-run",
        )
        inventor_sources = repository / "inventors"
        expected_inventor_members = set()
        for inventor_id in INVENTORS:
            source_root = inventor_sources / inventor_id
            for relative, source in _source_files(source_root).items():
                member = (
                    "workshop/contributors/_inventors/%s/%s"
                    % (inventor_id, relative)
                )
                expected_inventor_members.add(member)
                if member not in infos or archive.read(member) != source.read_bytes():
                    raise AssertionError("wheel Inventor asset differs: %s" % member)
                source_executable = bool(source.stat().st_mode & 0o111)
                wheel_executable = _zip_executable(infos[member])
                if source_executable != wheel_executable:
                    raise AssertionError(
                        "wheel Inventor executable mode differs: %s" % member
                    )
        observed_inventor_members = {
            name
            for name, info in infos.items()
            if name.startswith("workshop/contributors/_inventors/")
            and not info.is_dir()
        }
        if observed_inventor_members != expected_inventor_members:
            raise AssertionError("wheel bundled Inventor inventory differs")

        expected_schemas = {
            "workshop/%s/schemas/%s" % (owner, name)
            for name, owner in SCHEMA_OWNERS.items()
        }
        observed_schemas = {
            name
            for name in members
            if "/schemas/" in name and name.endswith(".schema.json")
        }
        if observed_schemas != expected_schemas:
            raise AssertionError("wheel schema inventory differs")

        runtime_data_roots = (
            "workshop/artifacts/schemas/",
            "workshop/contributors/_inventors/",
            "workshop/contributors/schemas/",
            "workshop/invent/skills/",
            "workshop/make/schemas/",
            "workshop/make/skills/",
            "workshop/release/skills/",
            "workshop/runtime/_agent_assets/",
            "workshop/runtime/schemas/",
        )
        unexpected_data = {
            name
            for name, info in infos.items()
            if name.startswith("workshop/")
            and not info.is_dir()
            and not name.endswith(".py")
            and not name.startswith(runtime_data_roots)
        }
        if unexpected_data:
            raise AssertionError(
                "wheel contains non-runtime package data: %r"
                % sorted(unexpected_data)
            )


def _install_wheel(
    wheel: Path,
    root: Path,
    *,
    with_dependencies: bool,
) -> tuple[Path, Path]:
    venv = root / "venv"
    _run((sys.executable, "-m", "venv", venv), cwd=root)
    python = _python_path(venv)
    command = [python, "-m", "pip", "install"]
    if not with_dependencies:
        command.append("--no-deps")
    command.append(wheel)
    _run(command, cwd=root)
    return python, _workshop_path(venv)


def _verify_declared_dependencies(python: Path, *, cwd: Path) -> None:
    _run((python, "-m", "pip", "check"), cwd=cwd)
    _run(
        (
            python,
            "-c",
            "import importlib.metadata as m; "
            "requirements = m.requires('autonomous-workshop') or []; "
            "assert 'cadgen==0.4.19' in requirements, requirements; "
            "assert 'pillow>=10.0' in requirements, requirements; "
            "assert 'psutil<8,>=7.2' in requirements, requirements; "
            "assert 'pypdf<7,>=6.16.2' in requirements, requirements; "
            "assert 'pypdfium2<6,>=5.13' in requirements, requirements; "
            "assert 'reportlab>=4.4' in requirements, requirements; "
            "assert m.version('cadgen') == '0.4.19'; "
            "import cadgen, io, psutil, pypdf, pypdfium2, reportlab; "
            "from PIL import Image; "
            "from reportlab.pdfgen import canvas; "
            "from workshop.release.native import validate_release_pdf_manual; "
            "assert all(module.__file__ for module in "
            "(cadgen, psutil, pypdf, pypdfium2, reportlab, Image)); "
            "buffer = io.BytesIO(); "
            "document = canvas.Canvas(buffer, pagesize=(297.64, 419.53)); "
            "document.drawString(36, 380, 'Installed Workshop PDF check'); "
            "document.drawString(36, 360, 'Open the box and begin safely.'); "
            "document.showPage(); document.save(); "
            "validate_release_pdf_manual(buffer.getvalue())",
        ),
        cwd=cwd,
    )


def _json(command, *, cwd: Path, environment) -> object:
    return json.loads(_run(command, cwd=cwd, environment=environment).stdout)


def _write_fake_codex(path: Path, python: Path) -> None:
    source = """#!%s
import json
import hashlib
import os
import re
import sys
import tomllib
from pathlib import Path

if sys.argv[1:] == ["--version"]:
    print("codex-cli 0.145.0")
    raise SystemExit(0)

run_root = Path.cwd()
wish = json.loads((run_root / "WISH.json").read_text(encoding="utf-8"))
stage = json.loads((run_root / "STAGE.json").read_text(encoding="utf-8"))
agent_root = run_root / ".codex" / "agents"
agent_entries = tuple(agent_root.iterdir())
if any(path.is_symlink() or not path.is_file() for path in agent_entries):
    raise RuntimeError("project-scoped custom agents must be regular files")
agent_files = sorted(path.name for path in agent_entries)
expected_inventor_ids = %r
if agent_files != [inventor_id + ".toml" for inventor_id in expected_inventor_ids]:
    raise RuntimeError(".codex/agents is not the complete Inventor roster")
inventor_ids = [Path(filename).stem for filename in agent_files]

def exact_block(instructions, label):
    encoded = instructions.encode("utf-8")
    encoded_label = label.encode("ascii")
    pattern = re.compile(
        rb"<<<AUTONOMOUS_WORKSHOP_EXACT_" + encoded_label
        + rb" bytes=([0-9]{1,9}) sha256=([0-9a-f]{64})>>>\\n"
    )
    match = pattern.search(encoded)
    if match is None:
        raise RuntimeError("custom Inventor agent exact source block is missing")
    size = int(match.group(1))
    start = match.end()
    end = start + size
    content = encoded[start:end]
    terminator = b"\\n<<<END_AUTONOMOUS_WORKSHOP_EXACT_" + encoded_label + b">>>"
    if encoded[end : end + len(terminator)] != terminator:
        raise RuntimeError("custom Inventor agent exact source block is malformed")
    if hashlib.sha256(content).hexdigest().encode("ascii") != match.group(2):
        raise RuntimeError("custom Inventor agent exact source block hash differs")
    return content

for inventor_id in inventor_ids:
    agent = tomllib.loads(
        (agent_root / (inventor_id + ".toml")).read_text(encoding="utf-8")
    )
    if set(agent) != {"name", "description", "developer_instructions"}:
        raise RuntimeError("custom Inventor agent fields are not minimal")
    if agent["name"] != inventor_id:
        raise RuntimeError("custom Inventor agent name differs from its roster path")
    description = agent["description"]
    instructions = agent["developer_instructions"]
    if (
        not isinstance(description, str)
        or not description.strip()
        or len(description) > 1024
        or not isinstance(instructions, str)
        or not instructions.strip()
        or len(instructions) > 8192
    ):
        raise RuntimeError("custom Inventor agent instructions are not bounded text")
    manifest = json.loads(exact_block(instructions, "MANIFEST"))
    taste = exact_block(instructions, "TASTE")
    skills = json.loads(exact_block(instructions, "SKILLS"))
    if (
        set(manifest) != {"schema_version", "id", "status", "source", "extensions"}
        or manifest["schema_version"] != 8
        or manifest["id"] != inventor_id
        or not isinstance(manifest["extensions"], list)
        or not manifest["extensions"]
        or not taste.startswith(b"---\\nname:")
        or skills
        != [
            {
                "name": extension["name"],
                "path": extension["path"],
                "artifact_sha256": extension["artifact_sha256"],
            }
            for extension in manifest["extensions"]
        ]
    ):
        raise RuntimeError("custom Inventor agent does not bind schema-v8 source bytes")
    required_references = [
        ".agents/skills/" + extension["name"] + "/SKILL.md"
        for extension in manifest["extensions"]
    ]
    if any(reference not in instructions for reference in required_references):
        raise RuntimeError("custom Inventor agent lacks an exact skill reference")
    if "catalog/inventors" in instructions:
        raise RuntimeError("custom Inventor agent refers to the removed product catalog")
    lower = instructions.casefold()
    if (
        "subagent" not in lower
        or "bounded" not in lower
        or "workshop manager" not in lower
        or "gate" not in lower
        or not any(
            phrase in lower
            for phrase in (
                "must not advance",
                "cannot advance",
                "do not advance",
                "may not advance",
                "never advance",
            )
        )
        or "effect" not in lower
        or not any(
            phrase in lower
            for phrase in (
                "must not perform",
                "cannot perform",
                "do not perform",
                "may not perform",
                "never perform",
            )
        )
    ):
        raise RuntimeError("custom Inventor agent is not a bounded child role")
(run_root / "agent-outcome.json").write_text(
    json.dumps(
        {
            "schema_version": 1,
            "kind": "autonomous-workshop.agent-outcome-proposal",
            "checkpoint_sha256": stage["checkpoint_sha256"],
            "subject_sha256": stage["subject_sha256"],
            "outcome": {
                "schema_version": 1,
                "stage": stage["stage"],
                "status": "waiting",
                "artifacts": [],
                "needs": ["installed-wheel fixture intentionally needs user input"],
                "proposed_transition": None,
            },
        },
        sort_keys=True,
    ) + "\\n",
    encoding="utf-8",
)
(run_root / "native-packaging-probe.json").write_text(
    json.dumps(
        {
            "arguments": sys.argv[1:],
            "custom_agent_ids": inventor_ids,
            "factory_visible": "FACTORY_PASSWORD" in os.environ,
            "prelaunch": {
                "agents": (run_root / "AGENTS.md").is_file(),
                "cad": (run_root / ".agents" / "skills" / "cad" / "SKILL.md").is_file(),
                "codex_agents": agent_root.is_dir(),
                "design_reference": (run_root / ".agents" / "skills" / "design-reference" / "SKILL.md").is_file(),
                "inventors": all(
                    (
                        run_root
                        / ".agents"
                        / "skills"
                        / (inventor_id + "-inventor")
                        / "SKILL.md"
                    ).is_file()
                    for inventor_id in expected_inventor_ids
                ),
                "no_catalog": not (run_root / "catalog").exists(),
                "private_temp": (
                    (run_root / ".tmp").is_dir()
                    and os.environ.get("TMPDIR") == str(run_root / ".tmp")
                    and os.environ.get("TMP") == str(run_root / ".tmp")
                    and os.environ.get("TEMP") == str(run_root / ".tmp")
                ),
                "root_marker": (run_root / ".workshop-product-run-root").is_file(),
                "image_to_cad": (run_root / ".agents" / "skills" / "image-to-cad" / "SKILL.md").is_file(),
                "manual_design": (run_root / ".agents" / "skills" / "manual-design" / "SKILL.md").is_file(),
                "stage": (run_root / "STAGE.json").is_file(),
                "step_parts": (run_root / ".agents" / "skills" / "step-parts" / "SKILL.md").is_file(),
                "workflow": (run_root / ".agents" / "skills" / "autonomous-workshop" / "SKILL.md").is_file(),
                "wish": (run_root / "WISH.json").is_file(),
            },
            "product_id": wish["product_id"],
            "prompt": sys.stdin.read(),
        },
        sort_keys=True,
    ) + "\\n",
    encoding="utf-8",
)
print(json.dumps({"type": "thread.started", "thread_id": %r}))
print(json.dumps({"type": "item.completed", "item": {"id": "message-1", "type": "agent_message", "text": "fixture waiting"}}))
print(json.dumps({"type": "turn.completed", "usage": {}}))
""" % (str(python), INVENTORS, CODEX_THREAD_ID)
    path.write_text(source, encoding="utf-8")
    path.chmod(0o700)


def _assert_materialized_tree(source_root: Path, target_root: Path) -> None:
    expected = _source_files(source_root)
    observed = _source_files(target_root)
    if set(observed) != set(expected):
        raise AssertionError("materialized asset inventory differs: %s" % target_root)
    for relative, source in expected.items():
        target = observed[relative]
        if target.read_bytes() != source.read_bytes():
            raise AssertionError("materialized asset bytes differ: %s" % target)
        expected_mode = 0o500 if source.stat().st_mode & 0o111 else 0o400
        if stat.S_IMODE(target.stat().st_mode) != expected_mode:
            raise AssertionError("materialized asset mode differs: %s" % target)


def _exact_custom_agent_block(instructions: str, label: str) -> bytes:
    encoded = instructions.encode("utf-8")
    match = re.search(
        (
            rb"<<<AUTONOMOUS_WORKSHOP_EXACT_"
            + label.encode("ascii")
            + rb" bytes=([0-9]{1,9}) sha256=([0-9a-f]{64})>>>\n"
        ),
        encoded,
    )
    if match is None:
        raise AssertionError("materialized Inventor lacks exact %s bytes" % label)
    size = int(match.group(1))
    start = match.end()
    end = start + size
    content = encoded[start:end]
    terminator = (
        b"\n<<<END_AUTONOMOUS_WORKSHOP_EXACT_"
        + label.encode("ascii")
        + b">>>"
    )
    if encoded[end : end + len(terminator)] != terminator:
        raise AssertionError("materialized Inventor %s framing differs" % label)
    if hashlib.sha256(content).hexdigest() != match.group(2).decode("ascii"):
        raise AssertionError("materialized Inventor %s hash differs" % label)
    return content


def _native_wish_smoke(
    *,
    workshop: Path,
    python: Path,
    root: Path,
    repository: Path,
    away: Path,
    environment: dict[str, str],
) -> None:
    fake_codex = root / "fake-codex"
    _write_fake_codex(fake_codex, python)
    environment = dict(environment)
    environment.update(
        {
            "WORKSHOP_CODEX_BIN": str(fake_codex),
            "FACTORY_PASSWORD": "must-not-reach-native-codex",
        }
    )
    receipt = _json(
        (
            workshop,
            "wish",
            "an installed native Workshop packaging probe",
            "--json",
        ),
        cwd=away,
        environment=environment,
    )
    if (
        receipt.get("kind") != "native-agent-run"
        or receipt.get("status") != "waiting"
        or receipt.get("stage") != "make"
        or receipt.get("effort") != "spark"
        or receipt.get("native_turns") != 1
        or receipt.get("action") != "started"
    ):
        raise AssertionError("installed Wish did not return a truthful wait: %r" % receipt)

    product_id = receipt["product_id"]
    workshop_home = Path(environment["WORKSHOP_HOME"])
    expected_workspace = workshop_home / "runs" / product_id / "workspace"
    expected_state = workshop_home / "state" / product_id
    probes = tuple(workshop_home.rglob("native-packaging-probe.json"))
    if probes != (expected_workspace / "native-packaging-probe.json",):
        raise AssertionError(
            "installed Wish did not launch from its toy project: expected %s, got %r; receipt=%r"
            % (
                expected_workspace / "native-packaging-probe.json",
                probes,
                receipt,
            )
        )
    workspace = probes[0].parent
    status = _json(
        (workshop, "status", product_id, "--json"),
        cwd=away,
        environment=environment,
    )
    if status.get("status") != "waiting" or status.get("session_status") != "checkpointed":
        raise AssertionError("installed Wish status lost its native checkpoint")

    codex_checkpoints = tuple(workshop_home.rglob("codex-session.json"))
    if codex_checkpoints != (expected_state / "codex-session.json",):
        raise AssertionError("installed Wish did not record exactly one Codex checkpoint")
    codex_checkpoint = json.loads(codex_checkpoints[0].read_text(encoding="utf-8"))
    if (
        codex_checkpoint.get("thread_id") != CODEX_THREAD_ID
        or stat.S_IMODE(codex_checkpoints[0].stat().st_mode) != 0o600
        or receipt["session"]["session"]["checkpoint_sha256"]
        != codex_checkpoint.get("checkpoint_sha256")
    ):
        raise AssertionError("installed Codex checkpoint binding is invalid")

    agent_checkpoint_path = expected_state / "agent-run.json"
    if not agent_checkpoint_path.is_file():
        raise AssertionError("installed Wish did not persist its host checkpoint")
    agent_checkpoint = json.loads(
        agent_checkpoint_path.read_text(encoding="utf-8")
    )
    roster = agent_checkpoint.get("inventor_roster")
    if (
        agent_checkpoint.get("schema_version") != 4
        or agent_checkpoint.get("effort") != "spark"
        or not isinstance(roster, list)
        or tuple(item.get("inventor_id") for item in roster) != INVENTORS
        or tuple(item.get("agent_path") for item in roster)
        != tuple(".codex/agents/%s.toml" % item for item in INVENTORS)
        or any(
            legacy in agent_checkpoint
            for legacy in ("catalog", "inventor_catalog", "persona_catalog")
        )
        or stat.S_IMODE(agent_checkpoint_path.stat().st_mode) != 0o600
    ):
        raise AssertionError("installed Wish host roster is not the schema-v4 Spark roster")

    probe = json.loads(
        (workspace / "native-packaging-probe.json").read_text(encoding="utf-8")
    )
    codex_arguments = probe["arguments"]
    argument_pairs = set(zip(codex_arguments, codex_arguments[1:]))
    if (
        probe["factory_visible"]
        or "--search" not in codex_arguments
        or ("--enable", "goals") not in argument_pairs
        or ("--enable", "multi_agent") not in argument_pairs
        or "--ask-for-approval" not in codex_arguments
        or "never" not in codex_arguments
        or "--strict-config" not in codex_arguments
        or ("--model", "gpt-5.6-sol") not in argument_pairs
        or "--sandbox" in codex_arguments
        or 'default_permissions="workshop-product-run"' not in codex_arguments
        or 'project_root_markers=[".workshop-product-run-root"]'
        not in codex_arguments
        or not any(
            argument.startswith(
                "permissions.workshop-product-run.workspace_roots="
            )
            and json.dumps(str(expected_workspace)) + "=true" in argument
            for argument in codex_arguments
        )
        or not any(
            argument.startswith("permissions.workshop-product-run.filesystem=")
            and '":root"="deny"' in argument
            and '":minimal"="read"' in argument
            and '":workspace_roots"={' in argument
            and '"."="write"' in argument
            and '".agents"="read"' in argument
            and '".codex"="read"' in argument
            and '"**/.env*"="deny"' in argument
            and json.dumps(str(expected_workspace.parent)) + '="deny"'
            in argument
            and json.dumps(str(expected_workspace)) + '="write"' in argument
            and json.dumps(str(expected_workspace / ".agents")) + '="read"'
            in argument
            and json.dumps(str(expected_workspace / ".codex")) + '="read"'
            in argument
            and json.dumps(str(expected_workspace / "**/.env*")) + '="deny"'
            in argument
            and "extends=" not in argument
            for argument in codex_arguments
        )
    ):
        raise AssertionError("installed native Codex boundary is incorrect")
    if tuple(probe["custom_agent_ids"]) != INVENTORS:
        raise AssertionError("installed toy has no complete custom Inventor roster")
    if probe["product_id"] != product_id or not all(probe["prelaunch"].values()):
        raise AssertionError("toy project was not populated before Codex launched")
    if "current make stage" not in probe["prompt"]:
        raise AssertionError("installed native Codex received the wrong stage prompt")

    constitution = repository / ".agents" / "product-run" / "AGENTS.md"
    if (workspace / "AGENTS.md").read_bytes() != constitution.read_bytes():
        raise AssertionError("materialized product-run constitution differs")
    if stat.S_IMODE((workspace / "AGENTS.md").stat().st_mode) != 0o400:
        raise AssertionError("materialized product-run constitution mode differs")
    marker = workspace / ".workshop-product-run-root"
    if (
        marker.read_bytes() != b"autonomous-workshop-product-run\n"
        or stat.S_IMODE(marker.stat().st_mode) != 0o400
    ):
        raise AssertionError("materialized product-run root marker differs")
    if stat.S_IMODE((workspace / ".tmp").stat().st_mode) != 0o700:
        raise AssertionError("product-run private temp directory mode differs")
    manager_instructions = (workspace / "AGENTS.md").read_text(
        encoding="utf-8"
    ).casefold()
    if not all(
        phrase in manager_instructions
        for phrase in (
            "workshop manager",
            "subagent",
            "spawn",
            "routing",
            "synthesis",
        )
    ):
        raise AssertionError("product-run constitution does not give Codex orchestration")
    _assert_materialized_tree(
        (
            repository
            / ".agents"
            / "product-run"
            / ".agents"
            / "skills"
            / "autonomous-workshop"
        ),
        workspace / ".agents" / "skills" / "autonomous-workshop",
    )
    for skill_name in SKILLS:
        _assert_materialized_tree(
            repository / "src" / "workshop" / SKILL_PATHS[skill_name],
            workspace / ".agents" / "skills" / skill_name,
        )
    expected_skill_names = {"autonomous-workshop", *SKILLS}
    if (workspace / "catalog").exists() or (workspace / "catalog").is_symlink():
        raise AssertionError("product run contains the removed Inventor catalog")
    agent_root = workspace / ".codex" / "agents"
    observed_agent_names = {
        path.name for path in agent_root.iterdir() if path.is_file()
    }
    if observed_agent_names != {"%s.toml" % item for item in INVENTORS}:
        raise AssertionError("materialized .codex/agents roster differs")
    if stat.S_IMODE(agent_root.stat().st_mode) != 0o500:
        raise AssertionError("materialized .codex/agents roster is mutable")
    for inventor_id in INVENTORS:
        source = repository / "inventors" / inventor_id
        manifest = json.loads((source / "inventor.json").read_text(encoding="utf-8"))
        if (
            manifest.get("schema_version") != 8
            or "lane" in manifest
            or "capabilities" in manifest
        ):
            raise AssertionError("source Inventor does not use schema version 8")
        agent_path = agent_root / (inventor_id + ".toml")
        if (
            agent_path.is_symlink()
            or not agent_path.is_file()
            or stat.S_IMODE(agent_path.stat().st_mode) != 0o400
        ):
            raise AssertionError("materialized Inventor agent is not immutable")
        agent = tomllib.loads(agent_path.read_text(encoding="utf-8"))
        if set(agent) != {"name", "description", "developer_instructions"}:
            raise AssertionError("materialized Inventor custom agent fields differ")
        if agent["name"] != inventor_id:
            raise AssertionError("materialized Inventor custom agent name differs")
        instructions = agent["developer_instructions"]
        if "catalog/inventors" in instructions:
            raise AssertionError("materialized Inventor retains a catalog reference")
        if _exact_custom_agent_block(instructions, "MANIFEST") != (
            source / "inventor.json"
        ).read_bytes():
            raise AssertionError("materialized Inventor manifest bytes differ")
        if _exact_custom_agent_block(instructions, "TASTE") != (
            source / "TASTE.md"
        ).read_bytes():
            raise AssertionError("materialized Inventor Taste bytes differ")
        expected_skill_bindings = [
            {
                "name": extension["name"],
                "path": extension["path"],
                "artifact_sha256": extension["artifact_sha256"],
            }
            for extension in manifest["extensions"]
        ]
        observed_skill_bindings = json.loads(
            _exact_custom_agent_block(instructions, "SKILLS")
        )
        if observed_skill_bindings != expected_skill_bindings:
            raise AssertionError("materialized Inventor skill binding differs")
        for extension in manifest["extensions"]:
            skill_name = extension["name"]
            expected_skill_names.add(skill_name)
            _assert_materialized_tree(
                source / extension["path"],
                workspace / ".agents" / "skills" / skill_name,
            )
    observed_skill_names = {
        path.name
        for path in (workspace / ".agents" / "skills").iterdir()
        if path.is_dir()
    }
    if observed_skill_names != expected_skill_names:
        raise AssertionError("materialized product-run skill inventory differs")


def acceptance(
    wheel: Path,
    repository: Path,
    *,
    with_dependencies: bool = False,
) -> None:
    _audit_wheel(wheel, repository)
    with tempfile.TemporaryDirectory(prefix="workshop-installed-wheel-") as temporary:
        root = Path(temporary).resolve()
        away = root / "outside-checkout"
        away.mkdir()
        python, workshop = _install_wheel(
            wheel,
            root,
            with_dependencies=with_dependencies,
        )
        environment = {
            name: os.environ[name]
            for name in (
                "HOME",
                "LANG",
                "LC_ALL",
                "LC_CTYPE",
                "PATH",
                "SYSTEMROOT",
                "TMPDIR",
            )
            if os.environ.get(name)
        }
        environment["WORKSHOP_HOME"] = str(root / "workshop-home")

        if with_dependencies:
            _verify_declared_dependencies(python, cwd=away)

        _run(
            (
                python,
                "-c",
                "import importlib.metadata as m; import workshop, cli.main; "
                "assert m.version('autonomous-workshop') == workshop.__version__",
            ),
            cwd=away,
            environment=environment,
        )
        skills = _json(
            (workshop, "skills", "list", "--json"),
            cwd=away,
            environment=environment,
        )
        if tuple(item["name"] for item in skills) != LISTED_MAKE_SKILLS:
            raise AssertionError("installed Make skill inventory is incomplete")
        schemas = set(
            _run(
                (workshop, "schemas", "list"), cwd=away, environment=environment
            ).stdout.splitlines()
        )
        if schemas != set(SCHEMA_OWNERS):
            raise AssertionError("installed schema inventory is incomplete")
        inventors = _json(
            (workshop, "inventors", "--json"), cwd=away, environment=environment
        )
        if tuple(item["id"] for item in inventors) != INVENTORS:
            raise AssertionError("installed inventor catalog is incomplete")
        wish_help = _run(
            (workshop, "wish", "--help"), cwd=away, environment=environment
        ).stdout
        if not all(
            token in wish_help for token in ("--effort", "spark", "forge", "quest")
        ):
            raise AssertionError("installed Wish help lacks selectable effort routes")
        if with_dependencies:
            _native_wish_smoke(
                workshop=workshop,
                python=python,
                root=root,
                repository=repository,
                away=away,
                environment=environment,
            )


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wheel", type=Path)
    parser.add_argument(
        "--with-dependencies",
        action="store_true",
        help="resolve declared dependencies, run pip check, and import the Release toolchain",
    )
    args = parser.parse_args(argv)
    repository = Path(__file__).resolve().parents[2]
    if args.wheel is not None:
        acceptance(
            args.wheel.resolve(strict=True),
            repository,
            with_dependencies=args.with_dependencies,
        )
    else:
        with tempfile.TemporaryDirectory(prefix="workshop-wheel-build-") as temporary:
            acceptance(
                _build_wheel(repository, Path(temporary)),
                repository,
                with_dependencies=args.with_dependencies,
            )
    print("installed-wheel-cli: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
