"""Shared measured design ledger; millimetres, user datums and disclosed repairs."""
from .joint_design import JOINT_DESIGN
DESIGN = {'schema_version': 1,
 'kind': 'ferro-line.selected-inventor-design',
 'product': 'Mintfin',
 'subject_sha256': '01177f3da85979b5ec17f7d074220321d41be9d8054287d00edea134a2766dac',
 'source': 'WISH.json; user-supplied measured numeric reference; no attached image or period '
           'prototype',
 'units': 'mm',
 'coordinate_system': 'X left/right, +Y nose to tail, +Z up',
 'envelope': {'x': [-66.5, 66.5], 'y': [-12, 157], 'z': [0, 93]},
 'colors': {'mint': '#a9cdbe',
            'cream': '#e6d6c3',
            'coral': '#ee8c7d',
            'charcoal': '#3d4138',
            'white': '#f6f5ef'},
 'segments': [{'id': 'body_01',
               'center': [0, 53.349999999999994, 25.7],
               'width': 57.5,
               'height': 44.4,
               'original_y_span': [45.3, 61.4],
               'shell_axial_length': 4.0,
               'section_scale': [0.76, 0.9, 0.975, 1, 0.975, 0.9, 0.76],
               'split': 'Y at widest section; front and rear printed section-down',
               'min_shell_wall': 1.6,
               'socket_wall': 2.0},
              {'id': 'body_02',
               'center': [0, 63.150000000000006, 24.700000000000003],
               'width': 59.6,
               'height': 45.1,
               'original_y_span': [53.6, 72.7],
               'shell_axial_length': 4.0,
               'section_scale': [0.76, 0.9, 0.975, 1, 0.975, 0.9, 0.76],
               'split': 'Y at widest section; front and rear printed section-down',
               'min_shell_wall': 1.6,
               'socket_wall': 2.0},
              {'id': 'body_03',
               'center': [0, 74.4, 24.7],
               'width': 53.1,
               'height': 41.9,
               'original_y_span': [64.9, 83.9],
               'shell_axial_length': 4.0,
               'section_scale': [0.76, 0.9, 0.975, 1, 0.975, 0.9, 0.76],
               'split': 'Y at widest section; front and rear printed section-down',
               'min_shell_wall': 1.6,
               'socket_wall': 2.0},
              {'id': 'body_04',
               'center': [0, 85.44999999999999, 25.0],
               'width': 46.9,
               'height': 39.6,
               'original_y_span': [76.1, 94.8],
               'shell_axial_length': 4.0,
               'section_scale': [0.76, 0.9, 0.975, 1, 0.975, 0.9, 0.76],
               'split': 'Y at widest section; front and rear printed section-down',
               'min_shell_wall': 1.6,
               'socket_wall': 2.0},
              {'id': 'body_05',
               'center': [0, 96.8, 27.85],
               'width': 36.2,
               'height': 31.5,
               'original_y_span': [87, 106.6],
               'shell_axial_length': 4.6,
               'section_scale': [0.76, 0.9, 0.975, 1, 0.975, 0.9, 0.76],
               'split': 'Y at widest section; front and rear printed section-down',
               'min_shell_wall': 1.6,
               'socket_wall': 2.0},
              {'id': 'body_06',
               'center': [0, 106.75, 32.85],
               'width': 27.1,
               'height': 24.3,
               'original_y_span': [96.9, 116.6],
               'shell_axial_length': 4.6,
               'section_scale': [0.76, 0.9, 0.975, 1, 0.975, 0.9, 0.76],
               'split': 'Y at widest section; front and rear printed section-down',
               'min_shell_wall': 1.6,
               'socket_wall': 2.0},
              {'id': 'body_07',
               'center': [0, 115.4, 40.0],
               'width': 19.4,
               'height': 19.4,
               'original_y_span': [105.8, 125],
               'shell_axial_length': 4.6,
               'section_scale': [0.76, 0.9, 0.975, 1, 0.975, 0.9, 0.76],
               'split': 'Y at widest section; front and rear printed section-down',
               'min_shell_wall': 1.6,
               'socket_wall': 2.0},
              {'id': 'body_08',
               'center': [0, 123.10000000000001, 48.6],
               'width': 13.6,
               'height': 16.2,
               'original_y_span': [114.4, 131.8],
               'shell_axial_length': 4.6,
               'section_scale': [0.76, 0.9, 0.975, 1, 0.975, 0.9, 0.76],
               'split': 'Y125.4 construction seam; front and rear printed section-down',
               'construction_seam_y': 125.4,
               'full_section_y': [123.1, 126.6],
               'min_shell_wall': 1.6,
               'socket_wall': 2.0}],
 'joint_slit_metadata_semantics': 'slit_length is the requested maximum slotted material length, '
                                  'not measured free finger span; slit_root_radius is an original '
                                  'design target, not a verified constructed radius',
 'face': {'origin': [0, -2.9, 36],
          'u_axis': [1, 0, 0],
          'v_axis': [0, 0.20791169081775934, 0.9781476007338057],
          'outward_normal': [0, -0.9781476007338057, 0.20791169081775934],
          'back_plane_local_n': 0,
          'plate_base_thickness': 2.6,
          'pocket_depth': 1.2,
          'rim_radial_gap': 0.25,
          'head_floor_local_n': 0.0,
          'head_to_plate_back_gap': 0.0,
          'outline': [[-30, 0],
                      [-27.6, 11],
                      [-20.7, 19],
                      [-13.8, 18],
                      [0, 13],
                      [13.8, 18],
                      [20.7, 19],
                      [27.6, 11],
                      [30, 0],
                      [26.5, -12],
                      [17.3, -17],
                      [0, -19],
                      [-17.3, -17],
                      [-26.5, -12]],
          'magnet_pockets': [{'u': -17,
                              'v': 6,
                              'diameter': 8.15,
                              'depth': 1.2,
                              'minimum_back_wall': 1.4},
                             {'u': 17,
                              'v': 6,
                              'diameter': 8.15,
                              'depth': 1.2,
                              'minimum_back_wall': 1.4},
                             {'u': 0,
                              'v': -13,
                              'diameter': 8.15,
                              'depth': 1.2,
                              'minimum_back_wall': 1.4}],
          'expressions': ['happy', 'sleepy'],
          'maximum_feature_projection_from_back': 9.3},
 'legs': {'articulated': False,
          'feet': [[-32, 50, 0], [32, 50, 0], [-32, 82, 0], [32, 82, 0]],
          'bounds_per_leg': [28, 27, 19],
          'attach_to': ['body_01', 'body_01', 'body_04', 'body_04'],
          'claws_per_paw': 3},
 'head': {'bounds_x': [-33.25, 33.25],
          'bounds_y': [-6, 51],
          'bounds_y_role': 'original untrimmed loft reference; not current constructed bounds',
          'posterior_stock_cut_y': 45.4,
          'socket_lip_end_y': 50.827856,
          'combined_bounds_status': 'requires final assembled measurement',
          'bounds_z': [13, 59],
          'max_section_y': 20,
          'split_y': 20,
          'min_wall': 1.6,
          'construction': 'smooth multi-ellipse loft; front and rear halves with section-down '
                          'print faces'},
 'tail': {'bounds_x': [-4, 4],
          'bounds_y': [118, 157],
          'bounds_z': [48, 93],
          'lobes': 5,
          'thickness': 8,
          'print': 'sagittal half sections flat, two bonded halves'},
 'novel_mechanisms': [{'id': 'split-finger-friction-ball-socket',
                       'definition': 'Spherical ball with 0.25 mm diametral running cavity, four '
                                     'slitted retaining fingers, 0.6 mm radial mouth undercut and '
                                     'four compliant preload lands; manually posed upward curl and '
                                     'axial twist.'},
                      {'id': 'indexed-three-magnet-face',
                       'definition': 'Three matching magnet pairs locate on a shared face datum; '
                                     'clearance lip indexes; magnet attraction retains.'}],
 'applied_rule_patterns': ['tolerance-test-first', 'printed-fit-clearance'],
 'physical_unverified': ['friction pose holding under gravity',
                         'snap insertion force',
                         'finger elastic recovery and fatigue',
                         'adhesive retention',
                         'magnet holding force and polarity',
                         'actual support-free print quality'],
 'construction_authority': 'Build and repair within these datums; gate results may require local '
                           'relieved interfaces, wider hidden socket bosses or local datum nudges. '
                           'Never claim the parameter table proves dynamic clearance.',
 'design_handoff_complete': True}
DESIGN["joints"] = JOINT_DESIGN
