"""Exact joint design datums, split from the shared design ledger without changes."""
JOINT_DESIGN = [{'id': 'J00',
  'parent': 'head',
  'child': 'body_01',
  'ball_center': [0, 48, 30],
  'rest_axis': [0, 1, 0],
  'ball_diameter': 10,
  'cavity_diameter': 10.25,
  'diametral_clearance': 0.25,
  'mouth_diameter': 8.8,
  'radial_retaining_undercut': 0.6,
  'lip_axial_position_from_center': 2.827856,
  'minimum_socket_wall': 2,
  'minimum_outer_diameter': 14.25,
  'slit_count': 4,
  'slit_width': 1,
  'slit_length': 8,
  'slit_root_radius': 0.5,
  'neck_diameter': 5.5,
  'pitch_range_degrees': [0, 25],
  'twist_range_degrees': [-20, 20],
  'yaw_range_degrees': [0, 0],
  'preload_lands': {'count': 4,
                    'radial_projection': 0.2,
                    'nominal_radial_interference': 0.075,
                    'axial_length': 1.6,
                    'circumferential_width': 1.6},
  'proof': 'CAD motion required; snap force, friction and recovery physically unverified'},
 {'id': 'J01',
  'parent': 'body_01',
  'child': 'body_02',
  'ball_center': [0, 57.85, 34],
  'rest_axis': [0, 1, 0],
  'ball_diameter': 10,
  'cavity_diameter': 10.25,
  'diametral_clearance': 0.25,
  'mouth_diameter': 8.8,
  'radial_retaining_undercut': 0.6,
  'lip_axial_position_from_center': 3.227856,
  'parent_clearance_lip_offset': 3.327856,
  'axial_mouth_land': 0.6,
  'minimum_socket_wall': 2,
  'minimum_outer_diameter': 14.25,
  'slit_count': 4,
  'slit_width': 1,
  'slit_length': 8,
  'slit_root_radius': 0.5,
  'neck_diameter': 5.1,
  'pitch_range_degrees': [0, 25],
  'twist_range_degrees': [-20, 20],
  'yaw_range_degrees': [0, 0],
  'preload_lands': {'count': 4,
                    'radial_projection': 0.2,
                    'nominal_radial_interference': 0.075,
                    'axial_length': 1.6,
                    'circumferential_width': 1.6},
  'proof': 'CAD motion required; snap force, friction and recovery physically unverified'},
 {'id': 'J02',
  'parent': 'body_02',
  'child': 'body_03',
  'ball_center': [0, 68.775, 33.5],
  'rest_axis': [0, 1, 0],
  'ball_diameter': 9.5,
  'cavity_diameter': 9.75,
  'diametral_clearance': 0.25,
  'mouth_diameter': 8.3,
  'radial_retaining_undercut': 0.6,
  'lip_axial_position_from_center': 2.557953,
  'minimum_socket_wall': 2,
  'minimum_outer_diameter': 13.75,
  'slit_count': 4,
  'slit_width': 1,
  'slit_length': 8,
  'slit_root_radius': 0.5,
  'neck_diameter': 5.225,
  'pitch_range_degrees': [0, 25],
  'twist_range_degrees': [-20, 20],
  'yaw_range_degrees': [0, 0],
  'preload_lands': {'count': 4,
                    'radial_projection': 0.2,
                    'nominal_radial_interference': 0.075,
                    'axial_length': 1.6,
                    'circumferential_width': 1.6},
  'proof': 'CAD motion required; snap force, friction and recovery physically unverified'},
 {'id': 'J03',
  'parent': 'body_03',
  'child': 'body_04',
  'ball_center': [0, 80.05, 33],
  'rest_axis': [0, 1, 0],
  'ball_diameter': 9.5,
  'cavity_diameter': 9.75,
  'diametral_clearance': 0.25,
  'mouth_diameter': 8.3,
  'radial_retaining_undercut': 0.6,
  'lip_axial_position_from_center': 2.557953,
  'minimum_socket_wall': 2,
  'minimum_outer_diameter': 13.75,
  'slit_count': 4,
  'slit_width': 1,
  'slit_length': 8,
  'slit_root_radius': 0.5,
  'neck_diameter': 5.225,
  'pitch_range_degrees': [0, 25],
  'twist_range_degrees': [-20, 20],
  'yaw_range_degrees': [0, 0],
  'preload_lands': {'count': 4,
                    'radial_projection': 0.2,
                    'nominal_radial_interference': 0.075,
                    'axial_length': 1.6,
                    'circumferential_width': 1.6},
  'proof': 'CAD motion required; snap force, friction and recovery physically unverified'},
 {'id': 'J04',
  'parent': 'body_04',
  'child': 'body_05',
  'ball_center': [0, 90.525, 33],
  'rest_axis': [0, 1, 0],
  'ball_diameter': 9.25,
  'cavity_diameter': 9.5,
  'diametral_clearance': 0.25,
  'mouth_diameter': 8.05,
  'radial_retaining_undercut': 0.6,
  'lip_axial_position_from_center': 3.122276,
  'axial_mouth_land': 0.6,
  'minimum_socket_wall': 2,
  'minimum_outer_diameter': 13.5,
  'slit_count': 4,
  'slit_width': 1,
  'slit_length': 8,
  'slit_root_radius': 0.5,
  'neck_diameter': 4.5,
  'pitch_range_degrees': [0, 25],
  'twist_range_degrees': [-20, 20],
  'yaw_range_degrees': [0, 0],
  'preload_lands': {'count': 4,
                    'radial_projection': 0.2,
                    'nominal_radial_interference': 0.075,
                    'axial_length': 1.6,
                    'circumferential_width': 1.6},
  'proof': 'CAD motion required; snap force, friction and recovery physically unverified'},
 {'id': 'J05',
  'parent': 'body_05',
  'child': 'body_06',
  'ball_center': [0, 101.525, 34],
  'rest_axis': [0, 1, 0],
  'ball_diameter': 9,
  'cavity_diameter': 9.25,
  'diametral_clearance': 0.25,
  'mouth_diameter': 7.8,
  'radial_retaining_undercut': 0.6,
  'lip_axial_position_from_center': 2.486086,
  'minimum_socket_wall': 2,
  'minimum_outer_diameter': 13.25,
  'slit_count': 4,
  'slit_width': 1,
  'slit_length': 8,
  'slit_root_radius': 0.5,
  'neck_diameter': 4.95,
  'pitch_range_degrees': [0, 25],
  'twist_range_degrees': [-20, 20],
  'yaw_range_degrees': [0, 0],
  'preload_lands': {'count': 4,
                    'radial_projection': 0.2,
                    'nominal_radial_interference': 0.075,
                    'axial_length': 1.6,
                    'circumferential_width': 1.6},
  'proof': 'CAD motion required; snap force, friction and recovery physically unverified'},
 {'id': 'J06',
  'parent': 'body_06',
  'child': 'body_07',
  'ball_center': [0, 111.075, 37.1],
  'rest_axis': [0, 1, 0],
  'ball_diameter': 9,
  'cavity_diameter': 9.25,
  'diametral_clearance': 0.25,
  'mouth_diameter': 7.8,
  'radial_retaining_undercut': 0.6,
  'lip_axial_position_from_center': 2.486086,
  'minimum_socket_wall': 2,
  'minimum_outer_diameter': 13.25,
  'slit_count': 4,
  'slit_width': 1,
  'slit_length': 8,
  'slit_root_radius': 0.5,
  'neck_diameter': 4.95,
  'pitch_range_degrees': [0, 25],
  'twist_range_degrees': [-20, 20],
  'yaw_range_degrees': [0, 0],
  'preload_lands': {'count': 4,
                    'radial_projection': 0.2,
                    'nominal_radial_interference': 0.075,
                    'axial_length': 1.6,
                    'circumferential_width': 1.6},
  'proof': 'CAD motion required; snap force, friction and recovery physically unverified'},
 {'id': 'J07',
  'parent': 'body_07',
  'child': 'body_08',
  'ball_center': [0, 119.25, 41.8],
  'rest_axis': [0, 1, 0],
  'ball_diameter': 9,
  'cavity_diameter': 9.25,
  'diametral_clearance': 0.25,
  'mouth_diameter': 7.8,
  'radial_retaining_undercut': 0.6,
  'lip_axial_position_from_center': 3.086086,
  'minimum_socket_wall': 2,
  'minimum_outer_diameter': 13.25,
  'slit_count': 4,
  'slit_width': 1,
  'slit_length': 8,
  'slit_root_radius': 0.5,
  'neck_diameter': 4.2,
  'pitch_range_degrees': [0, 25],
  'twist_range_degrees': [-20, 20],
  'yaw_range_degrees': [0, 0],
  'preload_lands': {'count': 4,
                    'radial_projection': 0.2,
                    'nominal_radial_interference': 0.075,
                    'axial_length': 1.6,
                    'circumferential_width': 1.6},
  'proof': 'CAD motion required; snap force, friction and recovery physically unverified'},
 {'id': 'J08',
  'parent': 'body_08',
  'child': 'tail_fan',
  'ball_center': [0, 128.0, 48.8],
  'rest_axis': [0, 1, 0],
  'ball_diameter': 9,
  'cavity_diameter': 9.25,
  'diametral_clearance': 0.25,
  'mouth_diameter': 7.8,
  'radial_retaining_undercut': 0.6,
  'lip_axial_position_from_center': 3.086086,
  'axial_mouth_land': 0.6,
  'minimum_socket_wall': 2,
  'minimum_outer_diameter': 13.25,
  'slit_count': 4,
  'slit_width': 1,
  'slit_length': 8,
  'slit_root_radius': 0.5,
  'neck_diameter': 4.2,
  'pitch_range_degrees': [0, 25],
  'twist_range_degrees': [-20, 20],
  'yaw_range_degrees': [0, 0],
  'preload_lands': {'count': 4,
                    'radial_projection': 0.2,
                    'nominal_radial_interference': 0.075,
                    'axial_length': 1.6,
                    'circumferential_width': 1.6},
  'proof': 'CAD motion required; snap force, friction and recovery physically unverified'}]
