from __future__ import annotations

import errno
from pathlib import Path
import runpy
import tempfile
import unittest
from unittest import mock


REPOSITORY = Path(__file__).resolve().parents[2]
VERIFY_PROJECT = (
    REPOSITORY / "src/workshop/make/skills/cad/scripts/verify_project"
)


class VerifyProjectCacheCleanupTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.remove_generation_cache = staticmethod(
            runpy.run_path(str(VERIFY_PROJECT))["_remove_generation_cache"]
        )

    def test_permission_fallback_removes_bytes_and_tolerates_empty_directories(self):
        with tempfile.TemporaryDirectory() as temporary:
            cache = Path(temporary) / "__cadgen__"
            nested = cache / "models" / "part.step.py" / "components"
            nested.mkdir(parents=True)
            (nested / "mesh.glb").write_bytes(b"mesh")
            (cache / "progress.json").write_bytes(b"{}")

            denied = PermissionError(errno.EPERM, "protected empty directory")
            with mock.patch("shutil.rmtree", side_effect=denied):
                self.remove_generation_cache(cache)

            if cache.exists():
                self.assertEqual(
                    [path for path in cache.rglob("*") if not path.is_dir()],
                    [],
                )

    def test_permission_fallback_fails_when_generated_bytes_cannot_be_removed(self):
        with tempfile.TemporaryDirectory() as temporary:
            cache = Path(temporary) / "__cadgen__"
            cache.mkdir()
            generated = cache / "mesh.glb"
            generated.write_bytes(b"mesh")

            denied = PermissionError(errno.EPERM, "protected generated bytes")
            original_unlink = Path.unlink

            def unlink(path: Path, *args, **kwargs):
                if path == generated:
                    raise denied
                return original_unlink(path, *args, **kwargs)

            with mock.patch("shutil.rmtree", side_effect=denied), mock.patch.object(
                Path, "unlink", unlink
            ):
                with self.assertRaises(PermissionError):
                    self.remove_generation_cache(cache)


if __name__ == "__main__":
    unittest.main()
