#!/usr/bin/env python3
"""Export, mesh-check, and slice Manhattan Nocturne's printable inventory.

The receipt is digital manufacturing evidence only.  It deliberately does not
claim that a physical print has succeeded or that the finished set feels good.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import subprocess
import tempfile
from pathlib import Path


PROJECT = Path(__file__).resolve().parents[1]

PARTS = (
    ("board", 1),
    ("stone_pawn", 8),
    ("stone_rook", 2),
    ("stone_knight", 2),
    ("stone_bishop", 2),
    ("stone_queen", 1),
    ("stone_king", 1),
    ("steel_pawn", 8),
    ("steel_rook", 2),
    ("steel_knight", 2),
    ("steel_bishop", 2),
    ("steel_queen", 1),
    ("steel_king", 1),
)

PROFILE_NAMES = (
    "p2s-machine-standard.json",
    "p2s-process-standard.json",
    "pla-basic-standard.json",
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def repo_root() -> Path:
    for parent in (PROJECT, *PROJECT.parents):
        if (parent / "skills/cad/scripts/export/__main__.py").is_file():
            return parent
    raise RuntimeError("could not find the Workshop repository root")


def run(command: list[str], *, timeout: int = 300) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=repo_root(),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=timeout,
        check=False,
    )


def require_ok(result: subprocess.CompletedProcess[str], label: str) -> None:
    if result.returncode:
        detail = (result.stderr or result.stdout).strip()[-2000:]
        raise RuntimeError(f"{label} failed ({result.returncode}): {detail}")


def parse_duration(value: str) -> int:
    units = {"d": 86400, "h": 3600, "m": 60, "s": 1}
    found = re.findall(r"(\d+)\s*([dhms])", value)
    if not found:
        raise ValueError(f"unparseable duration: {value!r}")
    return sum(int(number) * units[unit] for number, unit in found)


def one_match(pattern: str, text: str, label: str) -> str:
    match = re.search(pattern, text, re.MULTILINE)
    if not match:
        raise ValueError(f"G-code lacks {label}")
    return match.group(1).strip()


def parse_gcode(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8", errors="replace")
    generated_by = one_match(r"^; generated by (.+)$", text, "slicer identity")
    model_time = one_match(
        r"^; model printing time:\s*([^;]+);", text, "model printing time"
    )
    total_time = one_match(
        r"^; model printing time:[^;]+; total estimated time:\s*(.+)$",
        text,
        "total estimated time",
    )
    support = one_match(r"^; enable_support = (\d+)$", text, "support setting")
    return {
        "gcode_sha256": sha256(path),
        "gcode_bytes": path.stat().st_size,
        "generated_by": generated_by,
        "model_seconds": parse_duration(model_time),
        "total_seconds": parse_duration(total_time),
        "layers": int(one_match(r"^; total layer number:\s*(\d+)$", text, "layers")),
        "max_z_mm": float(one_match(r"^; max_z_height:\s*([0-9.]+)$", text, "max Z")),
        "filament_mm": float(
            one_match(r"^; filament used \[mm\] =\s*([0-9.]+)$", text, "filament mm")
        ),
        "filament_cm3": float(
            one_match(r"^; filament used \[cm3\] =\s*([0-9.]+)$", text, "filament volume")
        ),
        "filament_g": float(
            one_match(r"^; filament used \[g\] =\s*([0-9.]+)$", text, "filament mass")
        ),
        "filament_cost": float(
            one_match(r"^; filament cost =\s*([0-9.]+)$", text, "filament cost")
        ),
        "support_enabled": support != "0",
    }


def canonical_write(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def find_gcodes(folder: Path) -> list[Path]:
    paths = sorted(folder.glob("*.gcode"))
    if not paths:
        raise RuntimeError("OrcaSlicer returned success but produced no G-code")
    return paths


def slicer_command(
    orca: Path,
    datadir: Path,
    output: Path,
    profiles: tuple[Path, Path, Path],
    inputs: list[Path],
) -> list[str]:
    machine, process, filament = profiles
    return [
        str(orca),
        "--datadir",
        str(datadir),
        "--load-settings",
        f"{machine};{process}",
        "--load-filaments",
        str(filament),
        "--load-defaultfila",
        "--arrange",
        "1",
        "--slice",
        "0",
        "--outputdir",
        str(output),
        *(str(path) for path in inputs),
    ]


def slice_inputs(
    *, orca: Path, profiles: tuple[Path, Path, Path], inputs: list[Path], label: str
) -> tuple[list[dict[str, object]], dict[str, object]]:
    with tempfile.TemporaryDirectory(prefix=f"manhattan-{label}-") as raw:
        root = Path(raw)
        output = root / "out"
        output.mkdir()
        command = slicer_command(orca, root / "data", output, profiles, inputs)
        result = run(command, timeout=900)
        require_ok(result, f"OrcaSlicer {label}")
        rows = [parse_gcode(path) for path in find_gcodes(output)]
        warnings = [line for line in result.stderr.splitlines() if line.strip()]
        public_command = []
        for argument in command:
            value = str(argument)
            if value == str(orca):
                value = "${ORCASLICER_CLI}"
            elif value.startswith(str(root)):
                value = value.replace(str(root), "${SLICE_TMP}", 1)
            elif value.startswith(str(repo_root())):
                value = value.replace(str(repo_root()), "${WORKSHOP_ROOT}", 1)
            public_command.append(value)
        return rows, {
            "argv": public_command,
            "exit_code": result.returncode,
            "stderr": warnings,
            "stdout": [line for line in result.stdout.splitlines() if line.strip()],
        }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--orca",
        type=Path,
        default=Path(os.environ["ORCASLICER_CLI"]) if os.environ.get("ORCASLICER_CLI") else None,
        help="OrcaSlicer 2.3.2 executable (or set ORCASLICER_CLI)",
    )
    parser.add_argument(
        "--cad-python",
        type=Path,
        default=repo_root() / ".venv-cad/bin/python",
    )
    parser.add_argument("--skip-export", action="store_true")
    args = parser.parse_args()

    if args.orca is None or not args.orca.is_file():
        parser.error("--orca must point to the OrcaSlicer executable")
    if not args.cad_python.is_file():
        parser.error("--cad-python must point to the pinned CAD Python")

    version = run([str(args.orca), "--help"])
    require_ok(version, "OrcaSlicer version check")
    first_line = (version.stdout or version.stderr).splitlines()[0].strip()
    if first_line != "OrcaSlicer-2.3.2:":
        raise RuntimeError(f"expected OrcaSlicer 2.3.2, got {first_line!r}")

    export_dir = PROJECT / "exports/stl"
    log_dir = PROJECT / "validation/mesh-logs"
    thickness_dir = PROJECT / "validation/thickness-reports"
    export_dir.mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)
    thickness_dir.mkdir(parents=True, exist_ok=True)

    export_tool = repo_root() / "skills/cad/scripts/export"
    mesh_tool = repo_root() / "skills/cad/scripts/check_mesh"
    thickness_tool = repo_root() / "skills/cad/scripts/check_thickness"
    stls: dict[str, Path] = {}
    mesh_rows: list[dict[str, object]] = []

    for part, quantity in PARTS:
        source = PROJECT / f"part_{part}.step.py"
        stl = export_dir / f"part_{part}.stl"
        stls[part] = stl
        if not args.skip_export:
            exported = run(
                [
                    str(args.cad_python),
                    str(export_tool),
                    str(source),
                    "--stl",
                    str(stl),
                    "--mesh-tolerance",
                    "0.05",
                    "--mesh-angular-tolerance",
                    "0.25",
                    "--json",
                ]
            )
            require_ok(exported, f"export {part}")
        if not stl.is_file():
            raise RuntimeError(f"missing STL: {stl}")
        stl_arg = stl.relative_to(repo_root())
        checked = run(
            [str(args.cad_python), str(mesh_tool), str(stl_arg), "--bed", "256x256x256"]
        )
        require_ok(checked, f"mesh check {part}")
        log = log_dir / f"part_{part}.txt"
        log.write_text(checked.stdout, encoding="utf-8")
        thickness_report = thickness_dir / f"part_{part}.md"
        thickness_checked = run(
            [
                str(args.cad_python),
                str(thickness_tool),
                str(stl_arg),
                "--nozzle",
                "0.4",
                "--report",
                str(thickness_report.relative_to(repo_root())),
            ],
            timeout=900,
        )
        require_ok(thickness_checked, f"thickness check {part}")
        mesh_rows.append(
            {
                "part": part,
                "quantity": quantity,
                "source": source.relative_to(PROJECT).as_posix(),
                "source_sha256": sha256(source),
                "stl": stl.relative_to(PROJECT).as_posix(),
                "stl_sha256": sha256(stl),
                "stl_bytes": stl.stat().st_size,
                "mesh_log": log.relative_to(PROJECT).as_posix(),
                "mesh_log_sha256": sha256(log),
                "mesh_passed": True,
                "thickness_report": thickness_report.relative_to(PROJECT).as_posix(),
                "thickness_report_sha256": sha256(thickness_report),
                "thickness_nozzle_mm": 0.4,
                "thickness_passed": True,
            }
        )

    profile_paths = tuple(
        PROJECT / "validation/orca-profiles" / name for name in PROFILE_NAMES
    )
    profiles = (profile_paths[0], profile_paths[1], profile_paths[2])
    if any(not path.is_file() for path in profiles):
        raise RuntimeError("one or more pinned Orca profiles are missing")

    slice_rows: list[dict[str, object]] = []
    slice_invocations: list[dict[str, object]] = []
    for part, quantity in PARTS:
        gcodes, invocation = slice_inputs(
            orca=args.orca, profiles=profiles, inputs=[stls[part]], label=part
        )
        if len(gcodes) != 1:
            raise RuntimeError(f"single-part slice {part} produced {len(gcodes)} plates")
        metrics = gcodes[0]
        if not str(metrics["generated_by"]).startswith("OrcaSlicer 2.3.2 on "):
            raise RuntimeError(f"unexpected slicer identity for {part}")
        slice_rows.append(
            {
                "part": part,
                "quantity": quantity,
                **metrics,
                "quantity_total_model_seconds": int(metrics["model_seconds"]) * quantity,
                "quantity_total_filament_g": round(float(metrics["filament_g"]) * quantity, 3),
            }
        )
        invocation["label"] = part
        slice_invocations.append(invocation)

    inventory_inputs = [stls[part] for part, qty in PARTS if part != "board" for _ in range(qty)]
    inventory_gcodes, inventory_invocation = slice_inputs(
        orca=args.orca,
        profiles=profiles,
        inputs=inventory_inputs,
        label="all-32-pieces",
    )
    inventory_invocation["label"] = "all-32-pieces"
    slice_invocations.append(inventory_invocation)
    slicer_warnings = sorted(
        {
            line
            for invocation in slice_invocations
            for line in invocation["stderr"]
            if line.strip()
        }
    )

    separate_seconds = sum(int(row["quantity_total_model_seconds"]) for row in slice_rows)
    separate_grams = round(sum(float(row["quantity_total_filament_g"]) for row in slice_rows), 3)
    board_slice = next(row for row in slice_rows if row["part"] == "board")
    inventory_seconds = sum(int(row["model_seconds"]) for row in inventory_gcodes)
    inventory_grams = sum(float(row["filament_g"]) for row in inventory_gcodes)
    expected_piece_grams = round(
        sum(
            float(row["quantity_total_filament_g"])
            for row in slice_rows
            if row["part"] != "board"
        ),
        3,
    )
    inventory_delta_grams = round(inventory_grams - expected_piece_grams, 3)
    inventory_passed = (
        len(inventory_inputs) == 32
        and len(inventory_gcodes) == 1
        and abs(inventory_delta_grams) <= 2.0
    )
    packed_seconds = int(board_slice["model_seconds"]) + inventory_seconds
    packed_grams = round(float(board_slice["filament_g"]) + inventory_grams, 3)
    receipt = {
        "schema_version": 1,
        "product": "manhattan-nocturne",
        "evidence_class": "digital-slicer",
        "observed_at": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "passed": inventory_passed,
        "scope": {
            "unique_printable_entries": len(PARTS),
            "physical_parts": sum(quantity for _, quantity in PARTS),
            "board_count": 1,
            "piece_count": 32,
        },
        "slicer": {
            "name": "OrcaSlicer",
            "version": "2.3.2",
            "executable_sha256": sha256(args.orca),
            "profiles": [
                {
                    "path": path.relative_to(PROJECT).as_posix(),
                    "sha256": sha256(path),
                }
                for path in profiles
            ],
        },
        "validation_tools": {
            "receipt_writer_sha256": sha256(Path(__file__)),
            "export_main_sha256": sha256(export_tool / "__main__.py"),
            "export_cli_sha256": sha256(export_tool / "cli.py"),
            "check_mesh_sha256": sha256(mesh_tool),
            "check_thickness_sha256": sha256(thickness_tool),
        },
        "mesh_checks": mesh_rows,
        "unique_part_slices": slice_rows,
        "full_piece_inventory_slice": {
            "input_objects": len(inventory_inputs),
            "plates": len(inventory_gcodes),
            "plate_metrics": inventory_gcodes,
            "individual_slice_sum_filament_g": expected_piece_grams,
            "arranged_slice_filament_g": round(inventory_grams, 3),
            "arrangement_delta_filament_g": inventory_delta_grams,
            "passed": inventory_passed,
        },
        "estimated_totals": {
            "packed_model_seconds": packed_seconds,
            "packed_filament_g": packed_grams,
            "separate_part_model_seconds": separate_seconds,
            "separate_part_filament_g": separate_grams,
        },
        "slicer_warnings": slicer_warnings,
        "invocations": slice_invocations,
        "claims": {
            "exact_stls_are_watertight_and_within_the_declared_bed": True,
            "exact_stls_meet_the_two_line_0_8mm_wall_floor": True,
            "exact_stls_slice_with_pinned_profiles": True,
            "all_32_pieces_were_arranged_and_sliced_on_one_plate": inventory_passed,
            "physical_print_succeeded": False,
            "surface_finish_verified": False,
            "tactile_feel_verified": False,
            "durability_verified": False,
            "gcode_accepted_by_a_physical_printer": False,
        },
        "limitations": [
            "This is deterministic digital mesh and slicer evidence, not a physical print.",
            *(
                [
                    "Orca produced measured G-code with exit code zero but reported a profile end-G-code warning; verify the G-code on the target P2S before Deliver."
                ]
                if slicer_warnings
                else []
            ),
            "Physical finish, warp, tipping, handling, and durability remain for Deliver and Reviews.",
        ],
    }
    canonical_write(PROJECT / "validation/slicer-receipt.json", receipt)
    print(json.dumps({"passed": receipt["passed"], **receipt["scope"], **receipt["estimated_totals"]}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
