"""Engine-neutral CAD contracts; modeling engines remain replaceable adapters."""

from .contracts import (
    CadPart,
    CadProjectManifest,
    CadReleaseBundle,
    PhysicalClaim,
    VerificationCheck,
    VerificationReceipt,
    ValidatorRequirement,
    WORKSHOP_CHECKS,
    WORKSHOP_CHECK_MEASUREMENTS,
    WORKSHOP_CHECK_SUBSTRATES,
    WORKSHOP_REQUIRED_CHECKS,
    assert_release_ready,
)
from .mesh import (
    KERNEL_BODY_OBSERVATION_VERSION,
    STL_INSPECTION_RECEIPT_VERSION,
    UPSTREAM_MIT_NOTICE,
    UPSTREAM_SOURCE_COMMIT,
    UPSTREAM_SOURCE_PATHS,
    KernelBodyObservation,
    StlInspectionLimits,
    StlPathInspectionError,
    StlTopologyReceipt,
    fits_bed_envelope,
    inspect_stl_path,
    inspect_stl_topology,
)

__all__ = [
    "CadPart",
    "CadProjectManifest",
    "CadReleaseBundle",
    "KERNEL_BODY_OBSERVATION_VERSION",
    "KernelBodyObservation",
    "PhysicalClaim",
    "STL_INSPECTION_RECEIPT_VERSION",
    "StlInspectionLimits",
    "StlPathInspectionError",
    "StlTopologyReceipt",
    "UPSTREAM_MIT_NOTICE",
    "UPSTREAM_SOURCE_COMMIT",
    "UPSTREAM_SOURCE_PATHS",
    "VerificationCheck",
    "VerificationReceipt",
    "ValidatorRequirement",
    "WORKSHOP_CHECKS",
    "WORKSHOP_CHECK_MEASUREMENTS",
    "WORKSHOP_CHECK_SUBSTRATES",
    "WORKSHOP_REQUIRED_CHECKS",
    "assert_release_ready",
    "fits_bed_envelope",
    "inspect_stl_path",
    "inspect_stl_topology",
]
