"""Wish-to-inventor matching and handoff services."""

from workshop.match.handoff import (
    HANDOFF_KIND,
    MAX_HANDOFF_BYTES,
    RESULT_BINDING_FIELD,
    ManagerAssignmentHandoff,
    bind_manager_assignment_result,
    read_manager_assignment,
    validate_manager_assignment_result,
)
from workshop.match.semantic import CodexSemanticManager, DEFAULT_MANAGER_MODEL
from workshop.match.service import (
    CatalogPage,
    FinalistContext,
    InventorAssignment,
    InventorCard,
    InventorCatalog,
    InventorFinalist,
    InventorRetriever,
    InventorRetrieverRequired,
    NoInventorFit,
    RoutingContext,
    RoutingDecision,
    Shortlist,
    TasteFit,
    TasteJudge,
    TasteJudgeRequired,
    WorkshopManager,
    create_assignment,
    create_shortlist,
    discover_inventor_catalog,
    dispatch_assignment,
    load_finalists,
    retrieve_shortlist,
    select_inventor,
    shortlist_all,
)

__all__ = [
    "HANDOFF_KIND",
    "MAX_HANDOFF_BYTES",
    "RESULT_BINDING_FIELD",
    "CatalogPage",
    "CodexSemanticManager",
    "DEFAULT_MANAGER_MODEL",
    "FinalistContext",
    "InventorAssignment",
    "InventorCard",
    "InventorCatalog",
    "InventorFinalist",
    "InventorRetriever",
    "InventorRetrieverRequired",
    "ManagerAssignmentHandoff",
    "NoInventorFit",
    "RoutingContext",
    "RoutingDecision",
    "Shortlist",
    "TasteFit",
    "TasteJudge",
    "TasteJudgeRequired",
    "WorkshopManager",
    "bind_manager_assignment_result",
    "create_assignment",
    "create_shortlist",
    "discover_inventor_catalog",
    "dispatch_assignment",
    "load_finalists",
    "read_manager_assignment",
    "retrieve_shortlist",
    "select_inventor",
    "shortlist_all",
    "validate_manager_assignment_result",
]
