"""Finite rule audit, no AI, optimization, retry or playtest controller.

Source oracle: rank arithmetic + procedural geometry, from Leiden about.html.
Reskin model: named entities + explicit capture table + pre-enumerated lanes.
Both are authored here, so agreement is NOT independent verification of the
source. Hand-derived expected fixtures supplement comparison. No source code
from Leiden is copied or executed. Terminal draws follow prose, not the web
engine (whose development page records missing repetition detection).
"""
from collections import Counter
from hashlib import sha256
from pathlib import Path
import json

HERE = Path(__file__).resolve().parent
ALL = tuple((x, y) for x in range(7) for y in range(9))
WATER = {(x, y) for x in (1, 2, 4, 5) for y in (3, 4, 5)}
DENS = {0: (3, 0), 1: (3, 8)}
TRAPS = {0: {(2, 0), (3, 1), (4, 0)}, 1: {(2, 8), (3, 7), (4, 8)}}
RANKS = {"rat": 1, "cat": 2, "wolf": 3, "dog": 4,
         "panther": 5, "tiger": 6, "lion": 7, "elephant": 8}
NAMES = ("dust", "asteroid", "moon", "planet", "dwarf", "comet", "pulsar", "giant")
CAPTURES = {
    "dust": {"dust", "giant"},
    "asteroid": {"dust", "asteroid"},
    "moon": {"dust", "asteroid", "moon"},
    "planet": {"dust", "asteroid", "moon", "planet"},
    "dwarf": {"dust", "asteroid", "moon", "planet", "dwarf"},
    "comet": {"dust", "asteroid", "moon", "planet", "dwarf", "comet"},
    "pulsar": {"dust", "asteroid", "moon", "planet", "dwarf", "comet", "pulsar"},
    "giant": set(NAMES),
}

def xy(s):
    return ord(s[0]) - ord('a'), int(s[1]) - 1

def source_legal(board, turn, origin, dest):
    if origin not in board or dest not in ALL or origin == dest:
        return False
    side, rank = board[origin]
    if side != turn or dest == DENS[side]:
        return False
    occupant = board.get(dest)
    if occupant and occupant[0] == side:
        return False
    if dest in WATER and rank != 1:
        return False
    dx, dy = dest[0] - origin[0], dest[1] - origin[1]
    if abs(dx) + abs(dy) != 1:
        if rank not in (6, 7) or origin in WATER or bool(dx) == bool(dy):
            return False
        ux = (dx > 0) - (dx < 0)
        uy = (dy > 0) - (dy < 0)
        distance = abs(dx) + abs(dy)
        path = [(origin[0] + ux * i, origin[1] + uy * i) for i in range(1, distance)]
        if not path or not all(p in WATER and p not in board for p in path) or dest in WATER:
            return False
    if occupant is None:
        return True
    if dest in TRAPS[side]:
        return True  # defender is in attacker's trap; attacker restores rank on exit
    if rank == 1 and occupant[1] == 8:
        return origin not in WATER
    return rank >= occupant[1]

# Explicit lane topology, not generated by the source oracle's ray traversal.
LANES = {}
for row in (3, 4, 5):
    for left, right in ((0, 3), (3, 6)):
        path = tuple((x, row) for x in range(left + 1, right))
        LANES[((left, row), (right, row))] = path
        LANES[((right, row), (left, row))] = path
for col in (1, 2, 4, 5):
    path = tuple((col, row) for row in (3, 4, 5))
    LANES[((col, 2), (col, 6))] = path
    LANES[((col, 6), (col, 2))] = path

def reskin_legal(images, player, start, finish):
    moving = images.get(start)
    if moving is None or moving[0] != player or finish not in ALL:
        return False
    owner, identity = moving
    if finish == ((3, 0) if owner == 0 else (3, 8)):
        return False
    enemy = images.get(finish)
    if enemy and enemy[0] == owner:
        return False
    nearby = {(start[0] + 1, start[1]), (start[0] - 1, start[1]),
              (start[0], start[1] + 1), (start[0], start[1] - 1)}
    if finish not in nearby:
        corridor = LANES.get((start, finish))
        if identity not in {"comet", "pulsar"} or corridor is None:
            return False
        if set(corridor).intersection(images):
            return False
    if finish in WATER and identity != "dust":
        return False
    if enemy is None:
        return True
    mask = {(2, 0), (3, 1), (4, 0)} if owner == 0 else {(2, 8), (3, 7), (4, 8)}
    if finish in mask:
        return True
    if identity == "dust" and enemy[1] == "giant" and start in WATER:
        return False
    return enemy[1] in CAPTURES[identity]

def reskin(board):
    return {p: (owner, NAMES[rank - 1]) for p, (owner, rank) in board.items()}

def key(board, turn):
    return turn, tuple(sorted(board.items()))

def source_terminal(board, turn, history):
    for owner in (0, 1):
        if board.get(DENS[1-owner], (None,))[0] == owner:
            return f"win:{owner}"
        if not any(p[0] == 1-owner for p in board.values()):
            return f"win:{owner}"
    if history.count(key(board, turn)) >= 3:
        return "draw:repetition"
    if not any(source_legal(board, turn, start, end) for start in board for end in ALL):
        return "draw:stalemate"
    return "ongoing"

def reskin_terminal(images, player, exposure_log):
    home_south, home_north = images.get((3, 0)), images.get((3, 8))
    if home_north and home_north[0] == 0:
        return "win:0"
    if home_south and home_south[0] == 1:
        return "win:1"
    present = {v[0] for v in images.values()}
    if present == {0}:
        return "win:0"
    if present == {1}:
        return "win:1"
    if Counter(exposure_log)[key(images, player)] > 2:
        return "draw:repetition"
    choices = [True for end in ALL for start in images if reskin_legal(images, player, start, end)]
    return "ongoing" if choices else "draw:stalemate"

def advance(board, turn, origin, dest, legal):
    if not legal(board, turn, origin, dest):
        raise ValueError("illegal move")
    following = dict(board)
    following[dest] = following.pop(origin)
    return following, 1-turn

def audit():
    counts = Counter()
    def compare(group, board, turn, start, end, expected=None):
        a = source_legal(board, turn, start, end)
        b = reskin_legal(reskin(board), turn, start, end)
        assert a == b, (group, board, start, end, a, b)
        if expected is not None:
            assert a == expected, (group, board, start, end, expected, a)
        if a:
            after_a, next_a = advance(board, turn, start, end, source_legal)
            after_b, next_b = advance(reskin(board), turn, start, end, reskin_legal)
            assert reskin(after_a) == after_b and next_a == next_b
        counts[group] += 1

    assert RANKS['wolf'] == 3 and RANKS['dog'] == 4
    white = ['g3','b2','c3','f2','e3','a1','g1','a3']
    black = ['a7','f8','e7','b8','c7','g9','a9','g7']
    initial = {xy(p): (side, rank) for side, row in enumerate((white, black)) for rank,p in enumerate(row,1)}
    default = '0g3a7b2f8c3e7f2b8e3c7a1g9g1a9a3g7'
    pairs = [default[i:i+2] for i in range(1,len(default),2)]
    assert white == pairs[::2] and black == pairs[1::2] and len(initial) == 16
    assert len(set(NAMES)) == 8 and len(WATER) == 12
    counts['setup_and_inventory'] += 1
    for start in initial:
        for end in ALL:
            compare('full_initial_position', initial, 0, start, end)
    for side in (0,1):
        for rank in range(1,9):
            for start in ALL:
                if start in WATER and rank != 1 or start == DENS[side]:
                    continue
                for end in ALL:
                    compare('single_piece_all_destinations', {start:(side,rank)}, side, start,end)
            for defending in range(1,9):
                compare('all_64_rank_captures_each_side', {xy('a2'):(side,rank),xy('b2'):(1-side,defending)},side,xy('a2'),xy('b2'), rank >= defending or (rank,defending)==(1,8))
    # Hand-derived boundary outcomes: no source/reskin model supplies expectation.
    for side in (0,1):
        for a,b in [('a4','b4'),('b4','a4'),('b4','c4')]:
            compare('rat_boundary_and_swim', {xy(a):(side,1),xy(b):(1-side,1)},side,xy(a),xy(b),True)
        for a,b,attacker,defender,answer in [
            ('b4','a4',1,8,False), ('a3','b3',1,8,True),
            ('a3','b3',8,1,True), ('a4','b4',8,1,False),
            ('b4','a4',1,2,False)]:
            compare('rat_elephant_origin_exceptions', {xy(a):(side,attacker),xy(b):(1-side,defender)},side,xy(a),xy(b),answer)
        for (start,end), path in LANES.items():
            for rank in (6,7):
                compare('every_jump_route_empty', {start:(side,rank)},side,start,end,True)
                for block in path:
                    for rat_side in (0,1):
                        compare('every_jump_blocker_cell_both_teams', {start:(side,rank),block:(rat_side,1)},side,start,end,False)
                for defender in range(1,9):
                    compare('every_jump_rank_landing', {start:(side,rank),end:(1-side,defender)},side,start,end,rank>=defender)
                compare('friendly_jump_landing', {start:(side,rank),end:(side,2)},side,start,end,False)
            for rank in (1,2,3,4,5,8):
                compare('nonjumper_all_routes', {start:(side,rank)},side,start,end,False)
        for trap in TRAPS[side]:
            adjacent = next(p for p in ALL if abs(p[0]-trap[0])+abs(p[1]-trap[1])==1 and p not in DENS.values())
            for rank in range(1,9):
                for victim in range(1,9):
                    compare('enemy_traps_all_rank_pairs', {adjacent:(side,rank),trap:(1-side,victim)},side,adjacent,trap,True)
            compare('own_trap_no_weakening', {adjacent:(1-side,2),trap:(side,8)},1-side,adjacent,trap,False)
            compare('restore_rank_when_exiting', {trap:(1-side,8),adjacent:(side,7)},1-side,trap,adjacent,True)
        den = DENS[side]
        approach=(3,1 if side==0 else 7)
        for rank in range(1,9):
            compare('own_den_forbidden', {approach:(side,rank)},side,approach,den,False)
            compare('opponent_den_all_roles', {approach:(1-side,rank)},1-side,approach,den,True)
        compare('no_diagonal', {xy('a1'):(side,8)},side,xy('a1'),xy('b2'),False)
        compare('no_land_jump', {xy('a1'):(side,7)},side,xy('a1'),xy('c1'),False)
        compare('no_wrong_turn', {xy('a2'):(side,4)},1-side,xy('a2'),xy('b2'),False)
        compare('no_friendly_capture', {xy('a2'):(side,8),xy('b2'):(side,1)},side,xy('a2'),xy('b2'),False)

    def ending(label, board, turn, repeats, expected):
        images=reskin(board)
        a=source_terminal(board,turn,[key(board,turn)]*repeats)
        b=reskin_terminal(images,turn,[key(images,turn)]*repeats)
        assert a==b==expected,(label,a,b,expected)
        counts[label]+=1
    ending('stalemate_draw', {xy('a1'):(0,2),xy('a2'):(1,3),xy('b1'):(1,4)},0,1,'draw:stalemate')
    ending('ongoing_initial',initial,0,1,'ongoing')
    ending('twofold_not_draw',initial,0,2,'ongoing')
    ending('threefold_draw',initial,0,3,'draw:repetition')
    for side in (0,1):
        ending('elimination_victory',{xy('a2'):(side,2)},1-side,1,f'win:{side}')
        for rank in range(1,9):
            ending('den_entry_victory',{DENS[1-side]:(side,rank),xy('g5'):(1-side,2)},1-side,1,f'win:{side}')
    # A legal repeated trace checks transitions, turn order and history keys.
    board={xy('a2'):(0,2),xy('g8'):(1,2)}
    images=reskin(board); turn=0
    log_a=[key(board,turn)]; log_b=[key(images,turn)]
    cycle=[('a2','b2'),('g8','f8'),('b2','a2'),('f8','g8')]*2
    for i,(a,b) in enumerate(cycle):
        board,next_a=advance(board,turn,xy(a),xy(b),source_legal)
        images,next_b=advance(images,turn,xy(a),xy(b),reskin_legal)
        assert next_a==next_b and reskin(board)==images
        turn=next_a; log_a.append(key(board,turn)); log_b.append(key(images,turn))
        result_a=source_terminal(board,turn,log_a)
        result_b=reskin_terminal(images,turn,log_b)
        assert result_a==result_b==('draw:repetition' if i==7 else 'ongoing')
        counts['matched_legal_repetition_trace']+=1
    # Changing only the player to move is NOT the same repetition key.
    assert source_terminal(initial,0,[key(initial,0),key(initial,1),key(initial,1)])=='ongoing'
    assert reskin_terminal(reskin(initial),0,[key(reskin(initial),0),key(reskin(initial),1),key(reskin(initial),1)])=='ongoing'
    counts['repetition_side_to_move']+=1
    report={
        'status':'pass','kind':'finite-rules-equivalence-audit','playtest':False,
        'cases':sum(counts.values()),'categories':dict(sorted(counts.items())),
        'source':'https://liacs.leidenuniv.nl/~visjk/doushouqi/about.html',
        'setup_source':'https://liacs.leidenuniv.nl/~visjk/doushouqi/create.html',
        'source_nuance':'position.h corroborates trap-exit and water-origin semantics; its code was not copied or executed.',
        'method':'Two separately structured, locally authored models plus explicit expected fixtures; legal results compare next states and turns.',
        'limitations':['Finite fixture agreement is not an exhaustive proof over every reachable game state.',
                      'Both models were authored by the same agent, so shared interpretation errors remain possible.',
                      'No human play, physical comfort, print, motion, or independent source-engine validation is claimed.'],
        'artifact_sha256':{str(p.relative_to(HERE.parent)):sha256(p.read_bytes()).hexdigest() for p in (Path(__file__),HERE.parent/'RULES.md')},
    }
    (HERE/'audit-report.json').write_text(json.dumps(report,indent=2)+'\n')
    print(json.dumps({'status':report['status'],'cases':report['cases'],'report':str(HERE/'audit-report.json')}))

if __name__=='__main__':
    audit()
