"""The shared Workshop for autonomous inventors.

The public model is deliberately small: Wish and Taste guide a Make/Playtest
loop. Artifact, Runtime, Adapter, and Receipt are literal implementation types,
not extra invention stages.
"""

from .artifacts import (
    ArtifactManifest,
    build_artifact_manifest,
    build_pack,
    build_publish_packet,
)
from .attribution import attribute_product_description
from .cad import (
    CadReleaseBundle,
    KernelBodyObservation,
    StlInspectionLimits,
    StlPathInspectionError,
    StlTopologyReceipt,
    fits_bed_envelope,
    inspect_stl_path,
    inspect_stl_topology,
)
from .clockwork import (
    Clockwork,
    InspectionPolicy,
    PlaytestPolicy,
    Workflow,
    WorkflowSpec,
)
from .make import (
    CadBuildResult,
    CreationBrief,
    CreationResult,
    Forge,
    MakeResult,
    ProductForge,
    Wish,
    Workbench,
)
from .doors import (
    CadDoor,
    CadInspectionDoor,
    DeliveryDoor,
    InspectionDoor,
    ModelDoor,
    SendDoor,
    ShopDoorProtocol,
)
from .integrations import Adapter
from .inspection import Inspection
from .playtest import Playtest
from .deliver import DefaultDeliver
from .instructions import (
    DefaultInstructions,
    InstructionsSiteWriter,
    REQUIRED_PRODUCT_IMAGES,
)
from .gameplay import (
    ExecutableGame,
    GameTrace,
    LeagueConfig,
    LeagueReport,
    PlayerPolicy,
    RandomPlayer,
    run_game,
    run_league,
)
from .jobs import (
    CONCEPT_OVERALL_ROLES,
    ConceptBrief,
    ConceptComponent,
    ConceptContext,
    ConceptImages,
    CustomerReview,
    DeliverContext,
    Delivered,
    InstructionsContext,
    Feedback,
    Made,
    MakeContext,
    Need,
    PlaytestContext,
    Playtested,
    ProductInstructions,
    WaitingFor,
    WorkshopRun,
)
from .manager import (
    CatalogPage,
    FinalistContext,
    InventorAssignment,
    InventorCard,
    InventorCatalog,
    InventorFinalist,
    InventorRetriever,
    InventorRetrieverRequired,
    NoInventorFit,
    RoutingContext,
    RoutingDecision,
    Shortlist,
    TasteFit,
    TasteJudge,
    TasteJudgeRequired,
    WorkshopManager,
    create_assignment,
    create_shortlist,
    dispatch_assignment,
    discover_inventor_catalog,
    load_finalists,
    retrieve_shortlist,
    select_inventor,
    shortlist_all,
)
from .toys import (
    PLAYTHING_LANES,
    POST_DELIVERY_REVIEWS,
    ReviewsPolicy,
    TOY_TASKS,
    WORKSHOP_JOBS,
    ToyBlueprint,
    ToyTask,
    playful_make_request,
)
from .concept import (
    ConceptArtist,
    ConceptImageRequest,
    DefaultConcept,
    concept_handoff_text,
)
from .concept_artist_openrouter import OpenRouterConceptArtist
from .concept_explode_inspector import OpenAICompatibleExplodeInspector
from .env import load_dotenv
from .workshop import (
    CUSTOMIZATION_LEVELS,
    ConceptJob,
    InstructionsJob,
    Workshop,
    WorkshopTools,
)
from .errors import (
    AmbiguousEffectError,
    AmbiguousSendError,
    ConceptProviderError,
    EffectError,
    ReceiptError,
    SendError,
    StampError,
    WorkshopError,
)
from .lifecycle import GatePolicy, Pipeline, PipelineSpec
from .manifest import (
    WORKSHOP_FEATURES,
    InventorManifest,
    discover_inventors,
    load_manifest,
)
from .maker_mark import MAKER_MARK_MODES, MakerMark
from .models import (
    GateResult,
    InspectionResult,
    PlaytestResult,
    PublicationOutcome,
    PublicationReceipt,
    Receipt,
    SendResult,
    Stamp,
)
from .pack import (
    Artifact,
    ArtifactPlan,
    PackPlan,
    PackedArtifact,
    bundle_artifact,
    inspect_artifact,
    inspect_pack,
    pack_artifact,
    plan_artifact,
    plan_pack,
    seal_artifact,
)
from .ports import (
    AgentPort,
    CadPort,
    CadVerifierPort,
    DeliveryPort,
    EvaluatorPort,
    LaunchPort,
)
from .send import DEFAULT_SHOP_API, HttpResponse, Sender, ShopDoor
from .shop import ShopInstructionsWriter
from .runtime import Runtime
from .launch import DEFAULT_PORTAL_API, Launchpad, Portal, inspect_publish_packet
from .schemas import discover_schemas, resolve_schemas_root
from .scaffold import create_inventor
from .skills import SkillFingerprint, discover_skills, fingerprint_skill_tree
from .store import InventorStore
from .taste import (
    Taste,
    TasteHeader,
    TasteProfile,
    load_taste,
    load_taste_header,
    load_taste_profile,
)

__all__ = [
    # Toy Workshop 0.5 canonical surface.
    "Adapter",
    "AmbiguousEffectError",
    "Artifact",
    "ArtifactManifest",
    "ArtifactPlan",
    "attribute_product_description",
    "CadBuildResult",
    "CadReleaseBundle",
    "CatalogPage",
    "CONCEPT_OVERALL_ROLES",
    "ConceptArtist",
    "ConceptBrief",
    "ConceptComponent",
    "ConceptContext",
    "ConceptImageRequest",
    "ConceptImages",
    "ConceptJob",
    "ConceptProviderError",
    "concept_handoff_text",
    "OpenAICompatibleExplodeInspector",
    "OpenRouterConceptArtist",
    "CUSTOMIZATION_LEVELS",
    "CustomerReview",
    "DefaultConcept",
    "DefaultDeliver",
    "DefaultInstructions",
    "DeliverContext",
    "Delivered",
    "InstructionsContext",
    "InstructionsJob",
    "InstructionsSiteWriter",
    "EffectError",
    "ExecutableGame",
    "Feedback",
    "FinalistContext",
    "GameTrace",
    "InventorManifest",
    "InventorAssignment",
    "InventorCard",
    "InventorCatalog",
    "InventorFinalist",
    "InventorRetriever",
    "InventorRetrieverRequired",
    "KernelBodyObservation",
    "LeagueConfig",
    "LeagueReport",
    "MAKER_MARK_MODES",
    "MakeResult",
    "Made",
    "MakeContext",
    "MakerMark",
    "Need",
    "NoInventorFit",
    "PLAYTHING_LANES",
    "POST_DELIVERY_REVIEWS",
    "PlayerPolicy",
    "Playtest",
    "PlaytestContext",
    "PlaytestPolicy",
    "PlaytestResult",
    "Playtested",
    "ProductInstructions",
    "REQUIRED_PRODUCT_IMAGES",
    "RandomPlayer",
    "ReviewsPolicy",
    "Receipt",
    "ReceiptError",
    "Runtime",
    "RoutingContext",
    "RoutingDecision",
    "Shortlist",
    "SkillFingerprint",
    "StlInspectionLimits",
    "StlPathInspectionError",
    "StlTopologyReceipt",
    "Taste",
    "TasteHeader",
    "TasteFit",
    "TasteJudge",
    "TasteJudgeRequired",
    "WorkshopManager",
    "TOY_TASKS",
    "ToyBlueprint",
    "ToyTask",
    "WaitingFor",
    "Wish",
    "WORKSHOP_JOBS",
    "Workbench",
    "Workshop",
    "WorkshopRun",
    "WorkshopTools",
    "Workflow",
    "WorkflowSpec",
    "WorkshopError",
    "bundle_artifact",
    "create_assignment",
    "create_inventor",
    "create_shortlist",
    "dispatch_assignment",
    "discover_inventor_catalog",
    "discover_inventors",
    "discover_schemas",
    "discover_skills",
    "fingerprint_skill_tree",
    "fits_bed_envelope",
    "inspect_artifact",
    "inspect_stl_path",
    "inspect_stl_topology",
    "load_dotenv",
    "load_manifest",
    "load_finalists",
    "load_taste",
    "load_taste_header",
    "plan_artifact",
    "playful_make_request",
    "resolve_schemas_root",
    "retrieve_shortlist",
    "run_game",
    "run_league",
    "seal_artifact",
    "select_inventor",
    "shortlist_all",
    # Compatibility surface for Workshop 0.3 and older callers.
    "AgentPort",
    "AmbiguousSendError",
    "CadDoor",
    "CadInspectionDoor",
    "CadPort",
    "CadVerifierPort",
    "Clockwork",
    "CreationBrief",
    "CreationResult",
    "DEFAULT_PORTAL_API",
    "DEFAULT_SHOP_API",
    "DeliveryDoor",
    "DeliveryPort",
    "EvaluatorPort",
    "Forge",
    "GatePolicy",
    "GateResult",
    "HttpResponse",
    "Inspection",
    "InspectionDoor",
    "InspectionPolicy",
    "InspectionResult",
    "InventorStore",
    "LaunchPort",
    "Launchpad",
    "ModelDoor",
    "PackPlan",
    "PackedArtifact",
    "Pipeline",
    "PipelineSpec",
    "Portal",
    "ProductForge",
    "PublicationOutcome",
    "PublicationReceipt",
    "SendDoor",
    "SendError",
    "SendResult",
    "Sender",
    "ShopDoor",
    "ShopInstructionsWriter",
    "ShopDoorProtocol",
    "Stamp",
    "StampError",
    "TasteProfile",
    "WORKSHOP_FEATURES",
    "build_artifact_manifest",
    "build_pack",
    "build_publish_packet",
    "inspect_pack",
    "inspect_publish_packet",
    "load_taste_profile",
    "pack_artifact",
    "plan_pack",
]

__version__ = "0.5.0"
