"""The shared Workshop for autonomous inventors.

The public model is deliberately small: Wish and Taste guide a Make/Playtest
loop. Artifact, Runtime, Adapter, and Receipt are literal implementation types,
not extra invention stages.
"""

from .artifacts import (
    ArtifactManifest,
    build_artifact_manifest,
    build_pack,
    build_publish_packet,
)
from .attribution import attribute_product_description
from .batch import (
    BatchManagerIdentity,
    BatchPlan,
    BatchPlanItem,
    BatchPlanStore,
    BatchRequest,
    generate_batch_id,
    load_or_create_batch_manager_identity,
    parse_batch_file,
    parse_batch_input,
)
from .agent_invent import (
    CodexInventor,
    InventResearch,
    InventResearchProvider,
    InventResearchSource,
    InventResearchUnavailable,
)
from .cad import (
    CadReleaseBundle,
    KernelBodyObservation,
    StlInspectionLimits,
    StlPathInspectionError,
    StlTopologyReceipt,
    fits_bed_envelope,
    inspect_stl_path,
    inspect_stl_topology,
)
from .clockwork import (
    Clockwork,
    InspectionPolicy,
    PlaytestPolicy,
    Workflow,
    WorkflowSpec,
)
from .engine_provenance import (
    COMPONENT_STATES,
    DEFAULT_STAGE_PROVIDER_IDS,
    DEPENDENCY_KINDS,
    MANIFEST_COMPLETENESS,
    WORKSHOP_STAGES,
    EngineProvenanceManifest,
    PublicDependency,
    ResumeEngineCompatibility,
    StageComponentManifest,
    compare_engine_for_resume,
    describe_effective_engine,
)
from .make import (
    CadBuildResult,
    CreationBrief,
    CreationResult,
    Forge,
    MakeResult,
    ProductForge,
    Wish,
    Workbench,
    generate_wish_id,
)
from .doors import (
    CadDoor,
    CadInspectionDoor,
    DeliveryDoor,
    InspectionDoor,
    ModelDoor,
    SendDoor,
    ShopDoorProtocol,
)
from .integrations import Adapter
from .inspection import Inspection
from .playtest import Playtest
from .playtest_release import (
    CapabilityReleaseProof,
    ReleaseProofSource,
    playtest_release_needs,
)
from .lane_playtest_providers import (
    ClassicEvidenceProvider,
    PinnedCheckersRulesProvider,
    PreparedLaneRelease,
    ProviderIdentity,
    PublicScienceSource,
    ScienceAccuracyCase,
    ScienceComprehensionTrace,
    ScienceEvidenceProvider,
    ScienceSimplificationCheck,
    ScienceVerification,
    WorkshopLanePlaytestProviders,
    WorldConsentRecord,
    WorldEvidenceProvider,
    WorldLikenessCase,
    WorldReferenceMaterial,
    WorldVerification,
)
from .moving_machine import (
    MOVING_MACHINE_BINDING_KIND,
    MOVING_MACHINE_BINDING_VERSION,
    MovingMachineVerification,
    WorkshopMovingMachineVerifier,
    workshop_pinned_wear_model,
)
from .reviews import ReviewAuthentication, ReviewAuthenticator, review_sha256
from .sealed_draft import (
    CanonicalSlugDoor,
    SealedDraft,
    load_sealed_draft,
    publish_sealed_draft,
)
from .deliver import DefaultDeliver
from .delivery_evidence import (
    DeliveryEvidenceReceipt,
    validate_delivery_evidence_chain,
)
from .instructions import (
    DefaultInstructions,
    InstructionsSiteWriter,
)
from .gameplay import (
    ExecutableGame,
    GameTrace,
    LeagueConfig,
    LeagueReport,
    PlayerPolicy,
    RandomPlayer,
    run_game,
    run_league,
)
from .jobs import (
    CustomerReview,
    DeliverContext,
    Delivered,
    InstructionsContext,
    InventContext,
    Invented,
    Feedback,
    Made,
    MakeContext,
    Need,
    PlaytestContext,
    Playtested,
    ProductInstructions,
    WaitingFor,
    WorkshopRun,
)
from .manager import (
    CatalogPage,
    FinalistContext,
    InventorAssignment,
    InventorCard,
    InventorCatalog,
    InventorFinalist,
    InventorRetriever,
    InventorRetrieverRequired,
    NoInventorFit,
    RoutingContext,
    RoutingDecision,
    Shortlist,
    TasteFit,
    TasteJudge,
    TasteJudgeRequired,
    WorkshopManager,
    create_assignment,
    create_shortlist,
    dispatch_assignment,
    discover_inventor_catalog,
    load_finalists,
    register_workshop_engine,
    retrieve_shortlist,
    select_inventor,
    shortlist_all,
)
from .manager_services import (
    MANAGER_SERVICES_ENTRY_POINT_GROUP,
    ClassicRulesRegistry,
    DeliverFulfiller,
    FactoryCredentialBroker,
    ManagerProviderIdentity,
    ManagerServiceBinding,
    ManagerServices,
    WishResearchProvider,
    configured_manager_services,
    discover_manager_service_configurations,
    load_manager_services,
)
from .toys import (
    PLAYTHING_LANES,
    POST_DELIVERY_REVIEWS,
    ReviewsPolicy,
    TOY_TASKS,
    WORKSHOP_JOBS,
    ToyBlueprint,
    ToyTask,
    playful_make_request,
)
from .workshop import (
    CUSTOMIZATION_LEVELS,
    InstructionsJob,
    InventJob,
    TrustedWorkshopEngine,
    Workshop,
    WorkshopTools,
)
from .errors import (
    AmbiguousEffectError,
    AmbiguousSendError,
    EffectError,
    ReceiptError,
    SendError,
    StampError,
    WorkshopError,
)
from .lifecycle import GatePolicy, Pipeline, PipelineSpec
from .manifest import (
    WORKSHOP_FEATURES,
    InventorManifest,
    discover_inventors,
    load_manifest,
)
from .maker_mark import MAKER_MARK_MODES, MakerMark
from .models import (
    GateResult,
    InspectionResult,
    PlaytestResult,
    PublicationOutcome,
    PublicationReceipt,
    Receipt,
    SendResult,
    Stamp,
)
from .pack import (
    Artifact,
    ArtifactPlan,
    PackPlan,
    PackedArtifact,
    bundle_artifact,
    inspect_artifact,
    inspect_pack,
    pack_artifact,
    plan_artifact,
    plan_pack,
    seal_artifact,
)
from .ports import (
    AgentPort,
    CadPort,
    CadVerifierPort,
    DeliveryPort,
    EvaluatorPort,
    LaunchPort,
)
from .send import DEFAULT_SHOP_API, HttpResponse, Sender, ShopDoor
from .shop import ShopInstructionsWriter
from .runtime import Runtime
from .reward_loop import (
    RewardLoopBinding,
    RewardLoopJournal,
    RewardLoopResult,
    RewardSignal,
    RewardStep,
    run_reward_loop,
)
from .launch import DEFAULT_PORTAL_API, Launchpad, Portal, inspect_publish_packet
from .schemas import discover_schemas, resolve_schemas_root
from .scaffold import create_inventor
from .skills import SkillFingerprint, discover_skills, fingerprint_skill_tree
from .store import InventorStore
from .world_reference_vault import (
    AuthorizedWorldReference,
    CONSENT_CLAIM_BOUNDARY,
    LOCAL_STORAGE_SECURITY_BOUNDARY,
    MAX_WORLD_CONSENT_BYTES,
    MAX_WORLD_REFERENCE_BYTES,
    SUPPORTED_WORLD_CONSENT_METHODS,
    SUPPORTED_WORLD_MEDIA_TYPES,
    SUPPORTED_WORLD_SUBJECT_KINDS,
    WorldReferenceDescriptor,
    WorldReferenceReceipt,
    WorldReferenceService,
    WorldReferenceScope,
    WorldReferenceVault,
)
from .world_service import (
    EXTERNAL_WORLD_SERVICE_BOUNDARY,
    WORLD_SERVICE_BOUNDARIES,
    WorldEvidenceCase,
    WorldEvidenceReference,
    WorldInventInputs,
    WorldInventReference,
    WorldPlaytestEvidence,
    WorldPlaytestService,
    WorldProviderIdentity,
    prepare_world_invent_inputs,
    prepare_world_playtest_evidence,
)
from .taste import (
    Taste,
    TasteHeader,
    TasteProfile,
    load_taste,
    load_taste_header,
    load_taste_profile,
)

__all__ = [
    # Toy Workshop 0.5 canonical surface.
    "COMPONENT_STATES",
    "DEFAULT_STAGE_PROVIDER_IDS",
    "DEPENDENCY_KINDS",
    "MANIFEST_COMPLETENESS",
    "WORKSHOP_STAGES",
    "EngineProvenanceManifest",
    "PublicDependency",
    "ResumeEngineCompatibility",
    "StageComponentManifest",
    "compare_engine_for_resume",
    "describe_effective_engine",
    "ClassicEvidenceProvider",
    "AuthorizedWorldReference",
    "CONSENT_CLAIM_BOUNDARY",
    "LOCAL_STORAGE_SECURITY_BOUNDARY",
    "MAX_WORLD_CONSENT_BYTES",
    "MAX_WORLD_REFERENCE_BYTES",
    "MOVING_MACHINE_BINDING_KIND",
    "MOVING_MACHINE_BINDING_VERSION",
    "MovingMachineVerification",
    "PinnedCheckersRulesProvider",
    "PreparedLaneRelease",
    "ProviderIdentity",
    "PublicScienceSource",
    "ScienceAccuracyCase",
    "ScienceComprehensionTrace",
    "ScienceEvidenceProvider",
    "ScienceSimplificationCheck",
    "ScienceVerification",
    "SUPPORTED_WORLD_CONSENT_METHODS",
    "SUPPORTED_WORLD_MEDIA_TYPES",
    "SUPPORTED_WORLD_SUBJECT_KINDS",
    "WorkshopLanePlaytestProviders",
    "WorkshopMovingMachineVerifier",
    "WorldConsentRecord",
    "WorldEvidenceProvider",
    "WorldLikenessCase",
    "WorldReferenceMaterial",
    "WorldReferenceDescriptor",
    "WorldReferenceReceipt",
    "WorldReferenceService",
    "WorldReferenceScope",
    "WorldReferenceVault",
    "WorldVerification",
    "EXTERNAL_WORLD_SERVICE_BOUNDARY",
    "WORLD_SERVICE_BOUNDARIES",
    "WorldEvidenceCase",
    "WorldEvidenceReference",
    "WorldInventInputs",
    "WorldInventReference",
    "WorldPlaytestEvidence",
    "WorldPlaytestService",
    "WorldProviderIdentity",
    "prepare_world_invent_inputs",
    "prepare_world_playtest_evidence",
    "workshop_pinned_wear_model",
    "Adapter",
    "AmbiguousEffectError",
    "Artifact",
    "ArtifactManifest",
    "ArtifactPlan",
    "attribute_product_description",
    "CadBuildResult",
    "CadReleaseBundle",
    "CapabilityReleaseProof",
    "CatalogPage",
    "CodexInventor",
    "CUSTOMIZATION_LEVELS",
    "CustomerReview",
    "DefaultDeliver",
    "DefaultInstructions",
    "DeliverContext",
    "Delivered",
    "InstructionsContext",
    "InstructionsJob",
    "InstructionsSiteWriter",
    "InventContext",
    "Invented",
    "InventJob",
    "InventResearch",
    "InventResearchProvider",
    "InventResearchSource",
    "InventResearchUnavailable",
    "EffectError",
    "ExecutableGame",
    "Feedback",
    "FinalistContext",
    "GameTrace",
    "InventorManifest",
    "InventorAssignment",
    "InventorCard",
    "InventorCatalog",
    "InventorFinalist",
    "InventorRetriever",
    "InventorRetrieverRequired",
    "KernelBodyObservation",
    "LeagueConfig",
    "LeagueReport",
    "MAKER_MARK_MODES",
    "MakeResult",
    "Made",
    "MakeContext",
    "MakerMark",
    "Need",
    "NoInventorFit",
    "PLAYTHING_LANES",
    "POST_DELIVERY_REVIEWS",
    "PlayerPolicy",
    "Playtest",
    "PlaytestContext",
    "PlaytestPolicy",
    "PlaytestResult",
    "Playtested",
    "ProductInstructions",
    "RandomPlayer",
    "ReleaseProofSource",
    "ReviewsPolicy",
    "RewardLoopResult",
    "RewardLoopBinding",
    "RewardLoopJournal",
    "RewardSignal",
    "RewardStep",
    "Receipt",
    "ReceiptError",
    "SealedDraft",
    "Runtime",
    "RoutingContext",
    "RoutingDecision",
    "Shortlist",
    "SkillFingerprint",
    "StlInspectionLimits",
    "StlPathInspectionError",
    "StlTopologyReceipt",
    "Taste",
    "TasteHeader",
    "TasteFit",
    "TasteJudge",
    "TasteJudgeRequired",
    "TrustedWorkshopEngine",
    "WorkshopManager",
    "TOY_TASKS",
    "ToyBlueprint",
    "ToyTask",
    "WaitingFor",
    "Wish",
    "WORKSHOP_JOBS",
    "Workbench",
    "Workshop",
    "WorkshopRun",
    "WorkshopTools",
    "Workflow",
    "WorkflowSpec",
    "WorkshopError",
    "bundle_artifact",
    "create_assignment",
    "create_inventor",
    "create_shortlist",
    "dispatch_assignment",
    "discover_inventor_catalog",
    "discover_inventors",
    "discover_schemas",
    "discover_skills",
    "fingerprint_skill_tree",
    "generate_wish_id",
    "fits_bed_envelope",
    "inspect_artifact",
    "inspect_stl_path",
    "inspect_stl_topology",
    "load_manifest",
    "load_sealed_draft",
    "load_finalists",
    "load_taste",
    "load_taste_header",
    "plan_artifact",
    "playful_make_request",
    "playtest_release_needs",
    "publish_sealed_draft",
    "resolve_schemas_root",
    "retrieve_shortlist",
    "register_workshop_engine",
    "run_game",
    "run_league",
    "run_reward_loop",
    "seal_artifact",
    "select_inventor",
    "shortlist_all",
    # Compatibility surface for Workshop 0.3 and older callers.
    "AgentPort",
    "AmbiguousSendError",
    "CadDoor",
    "CadInspectionDoor",
    "CadPort",
    "CadVerifierPort",
    "CanonicalSlugDoor",
    "Clockwork",
    "CreationBrief",
    "CreationResult",
    "DEFAULT_PORTAL_API",
    "DEFAULT_SHOP_API",
    "DeliveryDoor",
    "DeliveryPort",
    "EvaluatorPort",
    "Forge",
    "GatePolicy",
    "GateResult",
    "HttpResponse",
    "Inspection",
    "InspectionDoor",
    "InspectionPolicy",
    "InspectionResult",
    "InventorStore",
    "LaunchPort",
    "Launchpad",
    "ModelDoor",
    "PackPlan",
    "PackedArtifact",
    "Pipeline",
    "PipelineSpec",
    "Portal",
    "ProductForge",
    "PublicationOutcome",
    "PublicationReceipt",
    "SendDoor",
    "SendError",
    "SendResult",
    "Sender",
    "ShopDoor",
    "ShopInstructionsWriter",
    "ShopDoorProtocol",
    "Stamp",
    "StampError",
    "TasteProfile",
    "WORKSHOP_FEATURES",
    "build_artifact_manifest",
    "build_pack",
    "build_publish_packet",
    "inspect_pack",
    "inspect_publish_packet",
    "load_taste_profile",
    "pack_artifact",
    "plan_pack",
]

__version__ = "0.5.0"
