"""The shared Workshop for autonomous inventors.

The public model is deliberately small: Wish and Taste guide a Make/Playtest
loop. Artifact, Runtime, Adapter, and Receipt are literal implementation types,
not extra invention stages.
"""

from .artifacts import (
    ArtifactManifest,
    build_artifact_manifest,
    build_pack,
    build_publish_packet,
)
from .cad import (
    CadReleaseBundle,
    KernelBodyObservation,
    StlInspectionLimits,
    StlPathInspectionError,
    StlTopologyReceipt,
    fits_bed_envelope,
    inspect_stl_path,
    inspect_stl_topology,
)
from .clockwork import (
    Clockwork,
    InspectionPolicy,
    PlaytestPolicy,
    Workflow,
    WorkflowSpec,
)
from .make import (
    CadBuildResult,
    CreationBrief,
    CreationResult,
    Forge,
    MakeResult,
    ProductForge,
    Wish,
    Workbench,
)
from .doors import (
    CadDoor,
    CadInspectionDoor,
    DeliveryDoor,
    InspectionDoor,
    ModelDoor,
    SendDoor,
    ShopDoorProtocol,
)
from .integrations import Adapter
from .inspection import Inspection
from .playtest import Playtest
from .deliver import DefaultDeliver
from .docs import DefaultDocs, REQUIRED_PRODUCT_IMAGES
from .gameplay import (
    ExecutableGame,
    GameTrace,
    LeagueConfig,
    LeagueReport,
    PlayerPolicy,
    RandomPlayer,
    run_game,
    run_league,
)
from .jobs import (
    DeliverContext,
    Delivered,
    DocsContext,
    Feedback,
    Made,
    MakeContext,
    Need,
    PlaytestContext,
    Playtested,
    ProductDocs,
    WaitingFor,
    WorkshopRun,
)
from .toys import (
    PLAYTHING_LANES,
    TOY_TASKS,
    WORKSHOP_JOBS,
    ToyBlueprint,
    ToyTask,
    playful_make_request,
)
from .workshop import CUSTOMIZATION_LEVELS, Workshop, WorkshopTools
from .errors import (
    AmbiguousEffectError,
    AmbiguousSendError,
    EffectError,
    ReceiptError,
    SendError,
    StampError,
    WorkshopError,
)
from .lifecycle import GatePolicy, Pipeline, PipelineSpec
from .manifest import (
    WORKSHOP_FEATURES,
    InventorManifest,
    discover_inventors,
    load_manifest,
)
from .maker_mark import MAKER_MARK_MODES, MakerMark
from .models import (
    GateResult,
    InspectionResult,
    PlaytestResult,
    PublicationOutcome,
    PublicationReceipt,
    Receipt,
    SendResult,
    Stamp,
)
from .pack import (
    Artifact,
    ArtifactPlan,
    PackPlan,
    PackedArtifact,
    bundle_artifact,
    inspect_artifact,
    inspect_pack,
    pack_artifact,
    plan_artifact,
    plan_pack,
    seal_artifact,
)
from .ports import (
    AgentPort,
    CadPort,
    CadVerifierPort,
    DeliveryPort,
    EvaluatorPort,
    LaunchPort,
)
from .send import DEFAULT_SHOP_API, HttpResponse, Sender, ShopDoor
from .runtime import Runtime
from .launch import DEFAULT_PORTAL_API, Launchpad, Portal, inspect_publish_packet
from .schemas import discover_schemas, resolve_schemas_root
from .skills import SkillFingerprint, discover_skills, fingerprint_skill_tree
from .store import InventorStore
from .taste import Taste, TasteProfile, load_taste, load_taste_profile

__all__ = [
    # Toy Workshop 0.5 canonical surface.
    "Adapter",
    "AmbiguousEffectError",
    "Artifact",
    "ArtifactManifest",
    "ArtifactPlan",
    "CadBuildResult",
    "CadReleaseBundle",
    "CUSTOMIZATION_LEVELS",
    "DefaultDeliver",
    "DefaultDocs",
    "DeliverContext",
    "Delivered",
    "DocsContext",
    "EffectError",
    "ExecutableGame",
    "Feedback",
    "GameTrace",
    "InventorManifest",
    "KernelBodyObservation",
    "LeagueConfig",
    "LeagueReport",
    "MAKER_MARK_MODES",
    "MakeResult",
    "Made",
    "MakeContext",
    "MakerMark",
    "Need",
    "PLAYTHING_LANES",
    "PlayerPolicy",
    "Playtest",
    "PlaytestContext",
    "PlaytestPolicy",
    "PlaytestResult",
    "Playtested",
    "ProductDocs",
    "REQUIRED_PRODUCT_IMAGES",
    "RandomPlayer",
    "Receipt",
    "ReceiptError",
    "Runtime",
    "SkillFingerprint",
    "StlInspectionLimits",
    "StlPathInspectionError",
    "StlTopologyReceipt",
    "Taste",
    "TOY_TASKS",
    "ToyBlueprint",
    "ToyTask",
    "WaitingFor",
    "Wish",
    "WORKSHOP_JOBS",
    "Workbench",
    "Workshop",
    "WorkshopRun",
    "WorkshopTools",
    "Workflow",
    "WorkflowSpec",
    "WorkshopError",
    "bundle_artifact",
    "discover_inventors",
    "discover_schemas",
    "discover_skills",
    "fingerprint_skill_tree",
    "fits_bed_envelope",
    "inspect_artifact",
    "inspect_stl_path",
    "inspect_stl_topology",
    "load_manifest",
    "load_taste",
    "plan_artifact",
    "playful_make_request",
    "resolve_schemas_root",
    "run_game",
    "run_league",
    "seal_artifact",
    # Compatibility surface for Workshop 0.3 and older callers.
    "AgentPort",
    "AmbiguousSendError",
    "CadDoor",
    "CadInspectionDoor",
    "CadPort",
    "CadVerifierPort",
    "Clockwork",
    "CreationBrief",
    "CreationResult",
    "DEFAULT_PORTAL_API",
    "DEFAULT_SHOP_API",
    "DeliveryDoor",
    "DeliveryPort",
    "EvaluatorPort",
    "Forge",
    "GatePolicy",
    "GateResult",
    "HttpResponse",
    "Inspection",
    "InspectionDoor",
    "InspectionPolicy",
    "InspectionResult",
    "InventorStore",
    "LaunchPort",
    "Launchpad",
    "ModelDoor",
    "PackPlan",
    "PackedArtifact",
    "Pipeline",
    "PipelineSpec",
    "Portal",
    "ProductForge",
    "PublicationOutcome",
    "PublicationReceipt",
    "SendDoor",
    "SendError",
    "SendResult",
    "Sender",
    "ShopDoor",
    "ShopDoorProtocol",
    "Stamp",
    "StampError",
    "TasteProfile",
    "WORKSHOP_FEATURES",
    "build_artifact_manifest",
    "build_pack",
    "build_publish_packet",
    "inspect_pack",
    "inspect_publish_packet",
    "load_taste_profile",
    "pack_artifact",
    "plan_pack",
]

__version__ = "0.5.0"
